"""Ready-made challenges for what people in Uzbekistan aim for today: DTM and IELTS, Russian,
AI and Python, freelancing and content, money, sleep, screen time, running and books.
Each has a week-by-week roadmap with a lesson per working day."""

from datetime import time
from typing import Any

from pit.catalog import catalog_id
from pit.modules.challenges.domain.challenge import Category, Challenge, ProofType, StakePolicy
from pit.modules.challenges.domain.roadmap import Milestone, Roadmap
from pit.modules.challenges.domain.schedule import Schedule, TaskSpec

PHOTO = frozenset({ProofType.PHOTO})
PHOTO_OR_TEXT = frozenset({ProofType.PHOTO, ProofType.TEXT})
MON_TO_SAT = range(6)
MON_WED_FRI = (0, 2, 4)


def week(theme: str, goal: str, *lessons: str) -> Milestone:
    return Milestone(theme=theme, goal=goal, lessons=lessons)


def task(
    key: str, title: str, minutes: int, *, required: bool = True, at: time | None = None
) -> TaskSpec:
    return TaskSpec(key=key, title=title, minutes=minutes, required=required, at=at)


def six_days(*tasks: TaskSpec) -> Schedule:
    return Schedule.by_weekday({d: list(tasks) for d in MON_TO_SAT})


TREND_ROADMAPS: dict[str, Roadmap] = {
    "dtm-math-60": Roadmap(
        outcome="DTM matematika bo'limida ishonchli 25+ to'g'ri javob, vaqtga sig'ib yechasiz",
        months=(
            "Asosiy mavzular takrorlangan, har kuni 20 test odatga aylangan",
            "To'liq blok vaqtga sig'ib yechiladi, xatolar ikki baravar kamaygan",
        ),
        weeks=(
            week(
                "Boshlang'ich holat",
                "Darajangizni bilasiz va har kungi ritm yo'lga qo'yilgan",
                "Diagnostika: 30 ta aralash test, natijani yozib qo'ying",
                "Sonlar, bo'linish belgilari, EKUK va EKUB",
                "Kasrlar va o'nli kasrlar bilan amallar",
                "Foiz masalalari: ulush, o'sish va kamayish",
                "Proporsiya va nisbatga oid masalalar",
                "Hafta testi: 20 ta savol, xatolar daftarini oching",
            ),
            week(
                "Algebra asoslari",
                "Ifodalarni soddalashtirish va tenglamalarni tez yechish",
                "Qisqa ko'paytirish formulalari",
                "Chiziqli tenglamalar va tengsizliklar",
                "Kvadrat tenglama, Viyet teoremasi",
                "Tenglamalar sistemasi",
                "Modulli tenglamalar",
                "Hafta testi: algebra, 25 daqiqada 20 savol",
            ),
            week(
                "Funksiyalar",
                "Grafikdan ma'lumot o'qish va funksiya xossalari",
                "Chiziqli va kvadrat funksiya grafigi",
                "Aniqlanish va qiymatlar sohasi",
                "Ko'rsatkichli funksiya va darajalar",
                "Logarifm: ta'rif va xossalar",
                "Logarifmik tenglamalar",
                "Hafta testi + xatolar daftarini takrorlash",
            ),
            week(
                "Trigonometriya",
                "Asosiy formulalar yod, tenglamalar ishonch bilan yechiladi",
                "Birlik aylana, sin va cos qiymatlari",
                "Asosiy trigonometrik ayniyatlar",
                "Keltirish formulalari",
                "Yig'indi va ikkilangan burchak formulalari",
                "Eng sodda trigonometrik tenglamalar",
                "Hafta testi: trigonometriya",
            ),
            week(
                "Planimetriya",
                "Shakllar yuzasi va burchaklarga oid masalalar",
                "Uchburchaklar: o'xshashlik va Pifagor teoremasi",
                "To'rtburchaklar va ularning yuzasi",
                "Aylana: vatar, urinma, ichki chizilgan burchak",
                "Muntazam ko'pburchaklar",
                "Koordinatalar tekisligida masalalar",
                "Hafta testi: geometriya",
            ),
            week(
                "Stereometriya va vektorlar",
                "Fazoviy shakllar hajmi va vektor amallari",
                "Prizma va parallelepiped",
                "Piramida va konus",
                "Silindr va shar",
                "Vektorlar: koordinatalar va skalyar ko'paytma",
                "Kombinatorika va ehtimollik asoslari",
                "Hafta testi: aralash 20 savol",
            ),
            week(
                "Progressiya va matnli masalalar",
                "Masala shartini tez tenglamaga aylantirasiz",
                "Arifmetik progressiya",
                "Geometrik progressiya",
                "Harakatga oid masalalar",
                "Ishga oid masalalar",
                "Aralashma va qotishmalar",
                "Hafta testi: matnli masalalar",
            ),
            week(
                "To'liq bloklar",
                "Haqiqiy imtihon tezligida ishlash",
                "To'liq blok: 30 savol, vaqt bilan",
                "Xatolar tahlili: eng ko'p xato qilingan 3 mavzu",
                "Zaif mavzu №1 ni qayta ishlash",
                "Zaif mavzu №2 ni qayta ishlash",
                "To'liq blok: 30 savol, vaqt bilan",
                "Natijalarni 1-haftadagi diagnostika bilan solishtiring",
            ),
            week(
                "Yakuniy tayyorgarlik",
                "Imtihonga xotirjam va tayyor kirasiz",
                "To'liq blok va tahlil",
                "Formulalar varag'ini bir marta to'liq takrorlash",
                "Yakuniy diagnostika: natija 1-kundan qancha oshdi?",
                "Keyingi oy uchun reja: qaysi mavzularni ushlab turish kerak",
            ),
        ),
    ),
    "ielts-60": Roadmap(
        outcome="IELTS formatini to'liq bilasiz, har bo'limda +0.5-1 ball o'sish uchun asos tayyor",
        months=(
            "Format o'zlashtirilgan, Listening va Reading'da barqaror natija",
            "Writing va Speaking mezonlarga mos, mock test vaqtga sig'adi",
        ),
        weeks=(
            week(
                "Format va boshlang'ich ball",
                "Har bo'lim qanday baholanishini bilasiz",
                "Diagnostika: Listening 1 test, ballni yozib qo'ying",
                "Reading: Skimming va scanning usuli",
                "Listening Section 1: raqamlar va ismlar",
                "Reading: True / False / Not Given",
                "Writing Task 1 tuzilmasi: overview nima?",
                "Speaking Part 1: o'zingiz haqingizda 10 savol",
            ),
            week(
                "Listening chuqur",
                "Section 2-3 dagi tuzoqlarni tanib olasiz",
                "Section 2: xarita va reja savollari",
                "Section 3: muhokamadagi fikrlarni ajratish",
                "Section 4: ma'ruza va eslatma yozish",
                "Sinonimlar: savol va audiodagi so'zlar farqi",
                "To'liq Listening test, vaqt bilan",
                "Xatolar tahlili va yangi so'zlar ro'yxati",
            ),
            week(
                "Reading tezligi",
                "Bitta passage 20 daqiqada",
                "Matching headings",
                "Sentence completion",
                "Multiple choice: noto'g'ri variantni chiqarib tashlash",
                "Matching information va features",
                "To'liq Reading test, vaqt bilan",
                "Akademik so'zlar: AWL ro'yxatidan 30 ta",
            ),
            week(
                "Writing Task 1",
                "Grafik, jadval va jarayonni 150+ so'zda tasvirlaysiz",
                "Line graph: trendni tasvirlash iboralari",
                "Bar chart va jadval: solishtirish",
                "Pie chart: ulushlar",
                "Process diagram: passiv nisbat",
                "Map: o'zgarishlarni tasvirlash",
                "To'liq Task 1, 20 daqiqada",
            ),
            week(
                "Writing Task 2",
                "250+ so'zli aniq tuzilmali esse",
                "Savol turlari: opinion, discussion, problem-solution",
                "Kirish qismi va thesis jumlasi",
                "Body paragraph: fikr, izoh, misol",
                "Bog'lovchilar va coherence",
                "Xulosa va umumiy xatolar",
                "To'liq Task 2, 40 daqiqada",
            ),
            week(
                "Speaking",
                "Ravon, mantiqli va uzunroq javob berasiz",
                "Part 1: javobni 2-3 jumlaga kengaytirish",
                "Part 2: 1 daqiqa tayyorlanib 2 daqiqa gapirish",
                "Part 2: hikoya qilish tuzilmasi",
                "Part 3: fikr bildirish va asoslash",
                "Talaffuz: urg'u va intonatsiya",
                "To'liq Speaking mock, ovozga yozib eshiting",
            ),
            week(
                "Lug'at va grammatika",
                "Band 7 ga xos so'z va murakkab jumlalar",
                "Collocations: make / do / take",
                "Murakkab jumlalar: relative clauses",
                "Shart gaplar",
                "Paraphrasing mashqi",
                "Idiomalarni o'rinli ishlatish",
                "Writing'dagi takroriy xatolarni tuzatish",
            ),
            week(
                "Mock testlar",
                "To'liq testni vaqtga sig'dirib yechasiz",
                "Mock: Listening + Reading",
                "Tahlil: qaysi savol turida xato ko'p",
                "Mock: Writing Task 1 + 2",
                "Writing'ni mezonlar bo'yicha o'zingiz baholang",
                "Mock: Speaking",
                "Zaif bo'lim ustida qo'shimcha mashq",
            ),
            week(
                "Yakun",
                "Imtihon kuniga reja tayyor",
                "Yakuniy mock: to'liq test",
                "Natijani 1-haftadagi diagnostika bilan solishtiring",
                "Imtihon kuni strategiyasi: vaqt va tartib",
                "Keyingi bosqich: qaysi bo'limni davom ettirish kerak",
            ),
        ),
    ),
    "russian-30": Roadmap(
        outcome="Kundalik vaziyatlarda rus tilida tushunasiz va o'zingizni erkin ifodalaysiz",
        weeks=(
            week(
                "Tanishuv",
                "O'zingiz va oilangiz haqida gapira olasiz",
                "Salomlashish va tanishish iboralari",
                "Oila va kasb haqida gapirish",
                "Raqamlar, vaqt va sana",
                "Kun tartibingizni tasvirlash",
                "Fe'lning hozirgi zamoni",
                "Savol berish: кто, что, где, когда",
                "Takrorlash: o'zingiz haqingizda 1 daqiqa gapiring",
            ),
            week(
                "Shahar va xizmatlar",
                "Do'kon, transport va kafeda bemalol muloqot",
                "Do'konda: narx so'rash va xarid",
                "Transport: yo'l so'rash",
                "Kafeda buyurtma berish",
                "Shifokorda: holatni tushuntirish",
                "Telefonda gaplashish",
                "Kelishiklar: predlojniy padej",
                "Takrorlash: dialog yozing va ovoz chiqarib o'qing",
            ),
            week(
                "O'tgan va kelasi zamon",
                "Bo'lgan voqeani hikoya qilasiz va reja tuzasiz",
                "O'tgan zamon: -л, -ла, -ли",
                "Kelasi zamon: буду + fe'l",
                "Dam olish kunini hikoya qilish",
                "Reja va istaklar: хочу, могу, надо",
                "Vinitelniy padej",
                "Sevimli film haqida gapirish",
                "Takrorlash: 2 daqiqalik hikoya",
            ),
            week(
                "Ish va o'qish",
                "Ishga oid suhbat va rasmiy murojaat",
                "Rezyume va o'zini tanishtirish",
                "Ish suhbati savollari",
                "Rasmiy xat va xabar yozish",
                "Fikr bildirish: я считаю, по-моему",
                "Roditelniy padej",
                "Uchrashuvni rejalashtirish",
                "Takrorlash: ish suhbati mashqi",
            ),
            week(
                "Erkin muloqot",
                "Tayyorgarliksiz 3 daqiqa gapirasiz",
                "Yangiliklar haqida fikr bildirish",
                "Bahs: rozilik va norozilik",
                "Yakuniy: 3 daqiqa o'zingiz tanlagan mavzuda gapiring",
            ),
        ),
    ),
    "ai-skills-21": Roadmap(
        outcome="ChatGPT, Claude va boshqa AI vositalari bilan o'qish va ishni tezlashtirasiz",
        weeks=(
            week(
                "AI bilan to'g'ri gaplashish",
                "Aniq prompt yozib, sifatli javob olasiz",
                "AI nima qila oladi va nima qila olmaydi",
                "Yaxshi prompt: rol, vazifa, kontekst, format",
                "Javobni bosqichma-bosqich yaxshilatish",
                "Misollar bilan o'rgatish (few-shot)",
                "AI xato qilganda: faktlarni tekshirish",
                "O'zingizga 5 ta tayyor prompt shabloni yozing",
            ),
            week(
                "O'qish va ish uchun",
                "Har kungi vazifalarda vaqtni tejaysiz",
                "Uzun matnni qisqartirish va konspekt",
                "Yangi mavzuni AI bilan o'rganish: savol-javob usuli",
                "Xat, e'lon va post yozdirish, keyin tahrirlash",
                "Jadval va rejalar tuzish",
                "Til o'rganishda AI: suhbat va xatolarni tuzatish",
                "Prezentatsiya rejasini AI bilan tayyorlang",
            ),
            week(
                "Kreativ va texnik",
                "AI'ni loyihangizda ishlatasiz",
                "Rasm yaratish vositalari va to'g'ri tavsif",
                "Kod yozishda AI yordamchi: tushuntirish va xato topish",
                "Ma'lumotlarni tahlil qilish: Excel/Sheets formulalari",
                "Maxfiylik: AI'ga nimani yubormaslik kerak",
                "Kichik loyiha: AI yordamida bitta muammoni hal qiling",
                "Natija: nima o'rgandingiz, keyingi qadam qanday",
            ),
        ),
    ),
    "python-30": Roadmap(
        outcome="Python asoslarini bilasiz va kichik foydali dastur yozib GitHub'ga joylaysiz",
        weeks=(
            week(
                "Asoslar",
                "O'zgaruvchi, tur va shartlar bilan ishlaysiz",
                "Python o'rnatish, birinchi dastur: print",
                "O'zgaruvchilar va ma'lumot turlari",
                "input() va turlarni o'zgartirish",
                "Shartlar: if, elif, else",
                "Mantiqiy operatorlar",
                "Mini dastur: yoshga qarab xabar beruvchi",
            ),
            week(
                "Takrorlash va kolleksiyalar",
                "Ro'yxatlar va sikllar bilan ishlaysiz",
                "for sikli va range",
                "while sikli",
                "Ro'yxatlar: qo'shish, o'chirish, saralash",
                "Lug'atlar (dict)",
                "Satrlar bilan ishlash",
                "Mini dastur: xarid ro'yxati",
            ),
            week(
                "Funksiyalar va fayllar",
                "Kodni funksiyalarga ajratib, faylga yozasiz",
                "Funksiya yaratish va parametrlar",
                "return va qiymat qaytarish",
                "Fayldan o'qish va yozish",
                "Xatolarni ushlash: try / except",
                "Modullar va import",
                "Mini dastur: kundalik (faylga saqlanadi)",
            ),
            week(
                "Amaliy kutubxonalar",
                "Internet va ma'lumotlar bilan ishlaysiz",
                "pip va virtual muhit",
                "requests: internetdan ma'lumot olish",
                "JSON bilan ishlash",
                "Sana va vaqt: datetime",
                "Klasslar: OOP'ga kirish",
                "Mini dastur: valyuta kursi ko'rsatuvchi",
            ),
            week(
                "Yakuniy loyiha",
                "Ishlaydigan loyiha GitHub'da",
                "Loyiha g'oyasi va rejasi (Telegram bot yoki CLI dastur)",
                "Asosiy funksiyalarni yozish",
                "Test qilish va xatolarni tuzatish",
                "README yozish va GitHub'ga joylash",
            ),
        ),
    ),
    "freelance-30": Roadmap(
        outcome="Frilans profilingiz tayyor, takliflar yuborilgan, birinchi buyurtmaga yo'l ochiq",
        weeks=(
            week(
                "Yo'nalish va ko'nikma",
                "Nima sotishingizni aniq bilasiz",
                "Ko'nikmalaringiz ro'yxati: nima qila olasiz",
                "Bozor: Upwork, Kwork, Fiverr va Telegram guruhlarida talab",
                "Bitta xizmatni tanlang va narxlarni o'rganing",
                "Raqobatchilarning 5 ta profilini tahlil qiling",
                "Xizmatingizni bir jumlada ta'riflang",
                "Ko'nikmani mustahkamlash: 1 soat amaliyot",
            ),
            week(
                "Portfolio",
                "3 ta namunaviy ish tayyor",
                "1-namunaviy ish: oddiy, lekin to'liq",
                "2-namunaviy ish",
                "3-namunaviy ish",
                "Har bir ish uchun qisqa tavsif: muammo → yechim → natija",
                "Portfolio sahifasi: Behance, GitHub yoki Telegram kanal",
                "Do'stlardan fikr so'rang va tuzating",
            ),
            week(
                "Profil",
                "Mijozni ishontiradigan profil",
                "Profil rasmi va sarlavha",
                "Tavsif: mijozga qanday foyda berasiz",
                "Xizmat paketlari va narxlar",
                "Ingliz tilida profil matni",
                "Profilni ikki platformada to'ldiring",
                "Profilni tekshirish ro'yxati bo'yicha yakunlang",
            ),
            week(
                "Takliflar",
                "Har kuni sifatli takliflar yuborasiz",
                "Yaxshi taklif (proposal) qanday yoziladi",
                "3 ta taklif yuboring",
                "3 ta taklif yuboring, matnni yaxshilang",
                "Tanishlaringizga xizmatingiz haqida yozing",
                "3 ta taklif yuboring",
                "Natijalar tahlili: qaysi taklifga javob keldi",
            ),
            week(
                "Mijoz bilan ishlash",
                "Birinchi buyurtmani muvaffaqiyatli topshirasiz",
                "Mijoz bilan muloqot va vazifani aniqlashtirish",
                "Muddat va to'lov shartlari",
                "Sharh (review) so'rash va keyingi buyurtma",
                "Keyingi oy rejasi: daromad maqsadi",
            ),
        ),
    ),
    "detox-14": Roadmap(
        outcome="Telefon sizni boshqarmaydi: ekran vaqti kamaygan, diqqat va uyqu yaxshilangan",
        weeks=(
            week(
                "Xabardorlik",
                "Vaqtingiz qayerga ketayotganini bilasiz",
                "Ekran vaqtini o'lchang: qaysi ilova ko'p vaqt oladi",
                "Bildirishnomalarni o'chiring: faqat odamlardan kelganlari qolsin",
                "Ijtimoiy tarmoqlarni bosh ekrandan olib tashlang",
                "Telefonni yotoqxonadan tashqarida zaryadlang",
                "Ovqat paytida telefonsiz",
                "Bo'shagan vaqtga nima qilasiz: ro'yxat tuzing",
                "Hafta yakuni: ekran vaqti qancha kamaydi",
            ),
            week(
                "Yangi odatlar",
                "Telefon o'rniga foydali odatlar",
                "Kulrang ekran rejimini yoqing",
                "Ijtimoiy tarmoqqa kuniga 2 ta belgilangan vaqt",
                "Yurish yoki sport: 30 daqiqa telefonsiz",
                "Kitob o'qing: 20 bet",
                "Do'st bilan yuzma-yuz uchrashuv",
                "Bir kunlik ijtimoiy tarmoq ro'zasi",
                "Yakun: qaysi qoidalar qoladi",
            ),
        ),
    ),
    "money-30": Roadmap(
        outcome="Pulingiz qayerga ketishini bilasiz, byudjet bor va jamg'arma boshlangan",
        weeks=(
            week(
                "Hisob",
                "Har bir xarajat yozib boriladi",
                "Daromad va majburiy xarajatlarni yozing",
                "Xarajatlarni toifalarga ajrating",
                "Kichik xarajatlar: kofe, taksi, yetkazib berish",
                "Obunalar: nimaga pul to'layapsiz",
                "Kreditlar va qarzlar ro'yxati",
                "Bank ilovasidagi xarajatlar tarixini ko'rib chiqing",
                "Hafta yakuni: eng katta 3 xarajat",
            ),
            week(
                "Byudjet",
                "Oylik reja: 50/30/20 qoidasi",
                "50/30/20 qoidasi nima",
                "Oylik byudjet tuzing",
                "Keraksiz xarajatni bittadan olib tashlang",
                "Xarid ro'yxati bilan bozorga boring",
                "Impulsiv xaridga 24 soat qoidasi",
                "Oilaviy byudjet haqida suhbat",
                "Hafta yakuni: rejaga amal qilindimi",
            ),
            week(
                "Jamg'arma",
                "Jamg'arish odati boshlandi",
                "Avval o'zingizga to'lang: daromad kuni jamg'arma",
                "Favqulodda jamg'arma: 3 oylik xarajat maqsadi",
                "Alohida jamg'arma hisobi yoki omonat",
                "Maqsad qo'ying: nima uchun jamg'aryapsiz",
                "Kichik jamg'arma: har kuni bir oz",
                "Inflyatsiya va pulning qadri",
                "Hafta yakuni: jamg'arma qancha",
            ),
            week(
                "Moliyaviy savod",
                "Qarz, foiz va sarmoyani tushunasiz",
                "Kredit foizi aslida qancha turadi",
                "Bo'lib to'lash: qachon foydali, qachon zarar",
                "Omonat va foiz turlari",
                "Sarmoyaning asosiy turlari va xavf",
                "Firibgarlik sxemalaridan saqlanish",
                "Qo'shimcha daromad g'oyalari",
                "Hafta yakuni: o'rganganlaringiz",
            ),
            week(
                "Yakun",
                "Keyingi oyga aniq moliyaviy reja",
                "Oy natijalari: qancha tejaldi",
                "Keyingi oy byudjeti",
            ),
        ),
    ),
    "sleep-21": Roadmap(
        outcome="23:00 gacha uxlaysiz, ertalab tetik turasiz va kun bo'yi kuch yetadi",
        weeks=(
            week(
                "Rejim",
                "Bir vaqtda yotish va turish",
                "Uyqu vaqtingizni tanlang: 7-8 soat",
                "Kofeinni 15:00 dan keyin ichmang",
                "Yotishdan 30 daqiqa oldin ekransiz",
                "Xona: qorong'i, salqin va jim",
                "Dam olish kunlari ham bir xil vaqt",
                "Kechki ovqat uxlashdan 2-3 soat oldin",
                "Hafta yakuni: o'zingizni qanday his qilyapsiz",
            ),
            week(
                "Chuqur uyqu",
                "Tez uxlab qolasiz, tunda kam uyg'onasiz",
                "Kechki marosim: dush, kitob, nafas mashqi",
                "Kunduzi 20 daqiqa quyosh nuri",
                "Kunduzgi uyqu 20 daqiqadan oshmasin",
                "4-7-8 nafas usuli",
                "Fikrlarni qog'ozga yozib bo'shatish",
                "Jismoniy faollik: kunduzi 30 daqiqa yurish",
                "Hafta yakuni: uyqu sifati",
            ),
            week(
                "Barqarorlik",
                "Yangi rejim odatga aylangan",
                "Ertalabki tartib: suv, yorug'lik, harakat",
                "Ekran vaqti kechqurun minimal",
                "Uyquni buzadigan narsalar ro'yxati",
                "Mehmondorchilik va kechikishlarda rejimni saqlash",
                "Natijani o'lchang: uyg'onish qanchalik oson",
                "Keyingi oy uchun qoidalaringiz",
                "Yakun: 21 kunlik natija",
            ),
        ),
    ),
    "pushup-30": Roadmap(
        outcome="Bir yondashuvda ko'p otjimaniya, kuchli ko'krak, yelka va qo'llar",
        weeks=(
            week(
                "Texnika",
                "To'g'ri texnika va boshlang'ich natija",
                "Test: bir yondashuvda nechta? Yozib qo'ying",
                "4 yondashuv x 6, oraliq 60 soniya",
                "4 x 8, tizzada bo'lsa ham to'g'ri texnika bilan",
                "5 x 8",
                "5 x 10",
                "Faol dam: plank 3 x 30 soniya",
            ),
            week(
                "Hajm",
                "Umumiy son kuniga 60 ga yetadi",
                "5 x 12",
                "6 x 10",
                "Keng qo'lli otjimaniya 4 x 10",
                "6 x 12",
                "Tor qo'lli otjimaniya 4 x 8",
                "Faol dam: plank 3 x 45 soniya",
            ),
            week(
                "Kuch",
                "Bir yondashuvda 25+",
                "5 x 15",
                "Piramida: 5-10-15-10-5",
                "6 x 15",
                "Sekin tushish: 4 x 10, har biri 3 soniya",
                "Test: bir yondashuvda maksimum",
                "Faol dam: cho'zilish 15 daqiqa",
            ),
            week(
                "Chidamlilik",
                "Kuniga 100 ta bo'lib bajariladi",
                "Jami 100 ta: qancha yondashuvda bo'lsa ham",
                "6 x 18",
                "Jami 100 ta, kamroq yondashuvda",
                "Oyoq ko'tarilgan otjimaniya 4 x 10",
                "7 x 18",
                "Faol dam: plank 3 x 60 soniya",
            ),
            week(
                "Yakun",
                "Natijani o'lchab, 1-kun bilan solishtirasiz",
                "Jami 120 ta",
                "Yakuniy test: bir yondashuvda maksimum — 1-kundagi bilan solishtiring",
            ),
        ),
    ),
    "run5k-60": Roadmap(
        outcome="5 km ni to'xtamasdan yugurasiz",
        weeks=(
            week(
                "Yurish va yugurish",
                "Yugurish ritmiga kirasiz",
                "5 daqiqa yurish, keyin 8 marta: 1 daqiqa yugurish + 1,5 daqiqa yurish",
                "Xuddi shunday: 8 x (1 daqiqa yugurish + 1,5 daqiqa yurish)",
                "8 x (1 daqiqa yugurish + 1,5 daqiqa yurish), tezlikni oshirmang",
            ),
            week(
                "Uzoqroq oraliqlar",
                "Ketma-ket 2 daqiqa yugurasiz",
                "6 x (1,5 daqiqa yugurish + 2 daqiqa yurish)",
                "6 x (2 daqiqa yugurish + 2 daqiqa yurish)",
                "6 x (2 daqiqa yugurish + 1,5 daqiqa yurish)",
            ),
            week(
                "5 daqiqa ketma-ket",
                "Nafas bilan bir maromda",
                "2 x (3 daqiqa yugurish + 3 daqiqa yurish) + 2 x 2 daqiqa",
                "3 x (4 daqiqa yugurish + 2 daqiqa yurish)",
                "2 x (5 daqiqa yugurish + 3 daqiqa yurish)",
            ),
            week(
                "10 daqiqa",
                "To'xtamasdan 10 daqiqa",
                "2 x (8 daqiqa yugurish + 3 daqiqa yurish)",
                "10 daqiqa yugurish, 3 daqiqa yurish, 5 daqiqa yugurish",
                "12 daqiqa to'xtamasdan",
            ),
            week(
                "20 daqiqa",
                "To'xtamasdan 20 daqiqa",
                "15 daqiqa yugurish, 2 daqiqa yurish, 5 daqiqa yugurish",
                "18 daqiqa to'xtamasdan",
                "20 daqiqa to'xtamasdan",
            ),
            week(
                "5 km",
                "5 km ni to'xtamasdan",
                "25 daqiqa to'xtamasdan",
                "28 daqiqa to'xtamasdan",
                "5 km to'xtamasdan — vaqtni yozib qo'ying!",
            ),
            week(
                "5 km barqaror",
                "5 km har safar to'xtamasdan",
                "5 km sekin, bir maromda",
                "30 daqiqa yengil yugurish",
                "5 km — vaqtingizni yaxshilashga urining",
            ),
            week(
                "Tezlik",
                "5 km vaqtingiz yaxshilanadi",
                "Interval: 6 x (1 daqiqa tez + 2 daqiqa sekin)",
                "35 daqiqa yengil yugurish",
                "Yakun: 5 km — 6-haftadagi vaqt bilan solishtiring!",
            ),
        ),
    ),
    "uzlit-30": Roadmap(
        outcome="O'zbek adabiyotining 3 ta durdona asari o'qilgan, fikrlaringiz yozib qo'yilgan",
        weeks=(
            week(
                "«O'tkan kunlar» — Abdulla Qodiriy",
                "Romanning birinchi yarmi o'qilgan",
                "Muallif va davr haqida 1 sahifa o'qing, keyin 25 bet",
                "Otabek va Kumushbibi: birinchi taassurot",
                "Toshkent va Marg'ilon: davr manzarasi",
                "Homid obrazi",
                "Yusufbek hoji: ota siymosi",
                "Sevimli parchangizni ko'chirib yozing",
                "Hafta fikri: roman sizga nimani o'rgatdi",
            ),
            week(
                "«O'tkan kunlar» yakuni",
                "Roman tugatilgan",
                "Zaynab obrazi",
                "Oila va urf-odatlar",
                "Fojia sabablari: sizning fikringiz",
                "Romanning tili: eskirgan so'zlar lug'ati",
                "So'nggi boblar",
                "Romanni 5 jumlada qayta hikoya qiling",
                "Do'stingizga tavsiya xatini yozing",
            ),
            week(
                "«Kecha va kunduz» — Cho'lpon",
                "Roman o'qilgan va tahlil qilingan",
                "Cho'lpon va uning davri",
                "Zebi obrazi",
                "Miryoqub va Akbarali mingboshi",
                "Romanning ramzlari: kecha va kunduz",
                "Til va tasvir: sevimli tasvirlaringiz",
                "Roman yakuni",
                "Hafta fikri: asar bugun ham dolzarbmi",
            ),
            week(
                "«Dunyoning ishlari» — O'tkir Hoshimov",
                "Hikoyalar to'plami o'qilgan",
                "Ona siymosi: birinchi hikoyalar",
                "Sizga eng ta'sir qilgan hikoya",
                "Muallif uslubi: oddiy so'z, chuqur ma'no",
                "Hikoyalar davomi",
                "O'z hayotingizdan bir xotira yozing",
                "To'plam yakuni",
                "Uch asarni solishtiring: qaysi biri sizga yaqin",
            ),
            week(
                "Yakun",
                "O'qish odati saqlanadi",
                "Keyingi oy uchun 3 ta kitob ro'yxatini tuzing",
                "Eng yaxshi iqtiboslaringizni do'stlaringizga ulashing",
            ),
        ),
    ),
    "content-30": Roadmap(
        outcome="Har kuni kontent chiqarasiz: Telegram, Reels yoki Shorts'da o'z auditoriyangiz",
        weeks=(
            week(
                "Boshlash",
                "Mavzu, platforma va birinchi postlar",
                "Mavzuingizni tanlang: nimani bilasiz va nimani yoqtirasiz",
                "Platforma: Telegram kanal, Instagram yoki YouTube Shorts",
                "Profil: nom, rasm, tavsif",
                "Birinchi post: o'zingiz va kanal haqida",
                "Foydali post: 3 ta maslahat",
                "Hafta tahlili: qaysi post ko'proq ko'rildi",
            ),
            week(
                "Format",
                "O'zingizga mos formatni topasiz",
                "Qisqa video: 30 soniyalik maslahat",
                "Ro'yxat formati: «5 ta xato»",
                "Shaxsiy hikoya",
                "Savol-javob: obunachilar savoliga javob",
                "Ilgari / keyin: natijani ko'rsatish",
                "Hafta tahlili va kontent-reja",
            ),
            week(
                "Sifat",
                "Sarlavha, birinchi 3 soniya va dizayn",
                "Sarlavha yozish: qiziqtiradigan va aniq",
                "Videoning birinchi 3 soniyasi",
                "Telefonda montaj: CapCut asoslari",
                "Muqova va oddiy dizayn: Canva",
                "Subtitr va ovoz sifati",
                "Hafta tahlili: ko'rishlar o'sdimi",
            ),
            week(
                "O'sish",
                "Auditoriya bilan muloqot va hamkorlik",
                "Izohlarga javob va so'rovnoma",
                "Boshqa kanal bilan hamkorlik (o'zaro reklama)",
                "Trend formatini o'z mavzuingizga moslash",
                "Eng yaxshi postni boshqa formatda qayta ishlash",
                "Post vaqtini sinab ko'rish",
                "Hafta tahlili: qaysi vaqt yaxshiroq",
            ),
            week(
                "Tizim",
                "Kontent chiqarish odatga aylangan",
                "Keyingi oy uchun 20 ta g'oya",
                "Oy natijalari: obunachilar va eng yaxshi postlar",
            ),
        ),
    ),
}


def trend(slug: str, **spec: Any) -> Challenge:
    return Challenge.create_template(
        challenge_id=catalog_id(slug),
        roadmap=TREND_ROADMAPS[slug],
        stake_policy=StakePolicy(allowed=True),
        **spec,
    )


def build_trends() -> list[Challenge]:
    return [
        trend(
            "dtm-math-60",
            title="DTM: matematika — 60 kun",
            description="Har kuni 20 ta test va xatolar tahlili. Mavzuma-mavzu takrorlash, "
            "oxirida to'liq bloklar vaqt bilan. Abituriyentlar uchun.",
            category=Category.STUDY,
            duration_days=60,
            difficulty=4,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda yechilgan matematik testlar yoki daftarda masala "
            "yechimlari ko'rinsin; matnda nechta test yechilgani va xatolar yozilsin.",
            default_schedule=six_days(
                task("tests", "20 ta test yechish", 45),
                task("review", "Xatolar tahlili", 15),
            ),
        ),
        trend(
            "ielts-60",
            title="IELTS 7.0 sari — 60 kun",
            description="Har kuni bitta bo'lim mashqi va akademik so'zlar. Format, strategiya "
            "va mock testlar — imtihonga tizimli tayyorgarlik.",
            category=Category.STUDY,
            duration_days=60,
            difficulty=4,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda IELTS mashqi (test, yozilgan esse, javoblar) "
            "ko'rinsin yoki matnda bajarilgan bo'lim va natija yozilsin.",
            default_schedule=six_days(
                task("practice", "IELTS mashqi: kunning bo'limi", 40),
                task("vocab", "15 ta akademik so'z", 15),
                task("speaking", "Speaking: 2 daqiqa ovozga yozib eshitish", 10, required=False),
            ),
        ),
        trend(
            "russian-30",
            title="Rus tilida erkin gapirish — 30 kun",
            description="Har kuni 10 ta kerakli jumla va 15 daqiqa ruscha video. Do'kon, ish "
            "va kundalik muloqot — bir oyda ishonch bilan.",
            category=Category.STUDY,
            duration_days=30,
            difficulty=2,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda rus tilida yozilgan jumlalar yoki mashq ko'rinsin, "
            "yoki matnda bugun o'rganilgan jumlalar yozilsin.",
            default_schedule=Schedule.every_day(
                task("phrases", "10 ta jumla o'rganish", 15),
                task("listen", "Ruscha video yoki podkast", 15),
            ),
        ),
        trend(
            "ai-skills-21",
            title="Sun'iy intellekt bilan ishlash — 21 kun",
            description="ChatGPT, Claude va boshqa AI vositalarini o'qish va ishda to'g'ri "
            "ishlatish: har kuni bitta amaliy vazifa.",
            category=Category.CODE,
            duration_days=21,
            difficulty=2,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda AI vositasi bilan bajarilgan ish (prompt va natija) "
            "ko'rinsin yoki matnda nima qilingani va natija yozilsin.",
            default_schedule=six_days(task("practice", "AI bilan amaliy vazifa", 30)),
        ),
        trend(
            "python-30",
            title="Python'ni noldan — 30 kun",
            description="Haftada 6 kun: yangi mavzu va mashq. Har hafta mini dastur, oxirida "
            "GitHub'da yakuniy loyiha. Dasturlashga birinchi qadam.",
            category=Category.CODE,
            duration_days=30,
            difficulty=3,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda Python kodi (redaktor yoki terminal) ko'rinsin yoki "
            "matnda yozilgan kod yoki GitHub havolasi bo'lsin.",
            default_schedule=six_days(task("code", "Python: mavzu va mashq", 60)),
        ),
        trend(
            "freelance-30",
            title="Frilans: birinchi buyurtmagacha — 30 kun",
            description="Xizmatni tanlash, portfolio, profil va har kuni takliflar. "
            "Upwork, Kwork va Telegram orqali birinchi daromadga yo'l.",
            category=Category.CUSTOM,
            duration_days=30,
            difficulty=3,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda portfolio ishi, profil yoki yuborilgan taklif "
            "ko'rinsin yoki matnda bugun nima qilingani yozilsin.",
            default_schedule=six_days(task("work", "Frilans: kunning qadami", 45)),
        ),
        trend(
            "detox-14",
            title="Raqamli detoks — 14 kun",
            description="Ekran vaqti kuniga 2 soatdan kam, tongning birinchi soati "
            "telefonsiz. Diqqat, uyqu va kayfiyat qaytadi.",
            category=Category.HEALTH,
            duration_days=14,
            difficulty=2,
            proof_types=PHOTO,
            verification_prompt="Rasmda telefonning ekran vaqti (Screen Time / Digital "
            "Wellbeing) kuniga 2 soatdan kam ekani ko'rinsin.",
            default_schedule=Schedule.every_day(
                task("screen", "Ekran vaqti 2 soatdan kam", 5),
                task("habit", "Kunning detoks qadami", 15),
            ),
        ),
        trend(
            "money-30",
            title="Pulni boshqarish — 30 kun",
            description="Har kuni xarajatlarni yozish va bitta moliyaviy mavzu. Byudjet, "
            "jamg'arma va qarzsiz hayot — bir oyda odat.",
            category=Category.CUSTOM,
            duration_days=30,
            difficulty=2,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda xarajatlar yozilgan daftar, jadval yoki ilova "
            "ko'rinsin yoki matnda bugungi xarajatlar va o'rganilgan mavzu yozilsin.",
            default_schedule=Schedule.every_day(
                task("track", "Bugungi xarajatlarni yozish", 10),
                task("learn", "Moliyaviy savod: kunning mavzusi", 15),
            ),
        ),
        trend(
            "sleep-21",
            title="Sog'lom uyqu — 21 kun",
            description="23:00 gacha uxlash va har kecha kichik bitta yangi odat. Ertalab "
            "tetik uyg'onish va kun bo'yi kuch.",
            category=Category.HEALTH,
            duration_days=21,
            difficulty=2,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda soat yoki telefon 23:00 dan oldingi vaqtni "
            "ko'rsatsin (yotishga tayyorgarlik) yoki matnda kechki tartib yozilsin.",
            default_schedule=Schedule.every_day(
                task("habit", "Kechki odat", 15, at=time(22, 30)),
                task("bed", "23:00 gacha yotish", 5, at=time(22, 50)),
            ),
        ),
        trend(
            "pushup-30",
            title="30 kunda 100 ta otjimaniya",
            description="Har kuni yangi reja: yondashuvlar asta-sekin ortadi. Oy oxirida "
            "kuniga 100+ ta otjimaniya — uyda, jihozsiz.",
            category=Category.SPORT,
            duration_days=30,
            difficulty=3,
            proof_types=PHOTO,
            verification_prompt="Rasmda otjimaniya qilayotgan foydalanuvchi yoki mashq "
            "jarayoni ko'rinsin.",
            default_schedule=six_days(task("pushups", "Otjimaniya: kunlik reja", 15)),
        ),
        trend(
            "run5k-60",
            title="Noldan 5 km yugurish — 60 kun",
            description="Haftada 3 marta yugurish va yurish navbatma-navbat. 6 haftada "
            "5 km ni to'xtamasdan yugurasiz, keyin vaqtingizni yaxshilaysiz.",
            category=Category.SPORT,
            duration_days=60,
            difficulty=3,
            proof_types=PHOTO,
            verification_prompt="Rasmda yugurish ilovasi yoki soatdagi masofa va vaqt, "
            "yoki yugurish jarayoni ko'rinsin.",
            default_schedule=Schedule.by_weekday(
                {d: [task("run", "Yugurish mashg'uloti", 30)] for d in MON_WED_FRI}
            ),
        ),
        trend(
            "uzlit-30",
            title="O'zbek adabiyoti: 30 kunda 3 asar",
            description="«O'tkan kunlar», «Kecha va kunduz» va «Dunyoning ishlari» — har "
            "kuni 25 bet va qisqa fikr. Klassikani qayta kashf eting.",
            category=Category.READING,
            duration_days=30,
            difficulty=2,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda ochiq kitob sahifasi ko'rinsin yoki matnda o'qilgan "
            "qism haqida mazmunli fikr yozilsin.",
            default_schedule=Schedule.every_day(
                task("read", "25 bet o'qish", 30),
                task("note", "Bitta fikr yoki iqtibos yozish", 5, required=False),
            ),
        ),
        trend(
            "content-30",
            title="Kontent yaratish — 30 kun",
            description="Har kuni bitta post yoki video: Telegram kanal, Instagram Reels "
            "yoki YouTube Shorts. Shaxsiy brend va auditoriya — noldan.",
            category=Category.CUSTOM,
            duration_days=30,
            difficulty=3,
            proof_types=PHOTO_OR_TEXT,
            verification_prompt="Rasmda joylangan post yoki video (kanal, Reels, Shorts) "
            "ko'rinsin yoki matnda post havolasi bo'lsin.",
            default_schedule=six_days(task("post", "Bitta kontent tayyorlash va joylash", 45)),
        ),
    ]
