"""Roadmaps of the ready-made challenges: a theme and a goal per week, and for skill
challenges a lesson per working day — so every day moves you further."""

from pit.modules.challenges.domain.roadmap import Milestone, Roadmap


def week(theme: str, goal: str, *lessons: str) -> Milestone:
    return Milestone(theme=theme, goal=goal, lessons=lessons)


ROADMAPS: dict[str, Roadmap] = {
    "sport-21": Roadmap(
        outcome="Mashq odatga aylangan, kuch va chidamlilik 1-kundagidan sezilarli yuqori",
        weeks=(
            week(
                "Moslashuv",
                "To'g'ri texnika va har kuni mashq qilish ritmi",
                "Butun tana: o'tirib-turish va otjimaniya texnikasi",
                "Kardio: 20 daqiqa yengil yugurish",
                "Oyoq va dumba mashqlari",
                "Ko'krak, yelka va triceps",
                "Orqa va biceps",
                "Faol dam: cho'zilish va bo'g'imlar harakati",
            ),
            week(
                "Kuch oshadi",
                "Yuklama oshadi, mashqlar osonroq bajariladi",
                "Butun tana: 3 aylana, og'irlik oshadi",
                "Intervalli kardio: 6 marta 1 daqiqa tez",
                "Oyoq: hamla va sakrashlar",
                "Yuqori tana: supersetlar",
                "Qorin va plank",
                "Uzoq yugurish: 30 daqiqa",
            ),
            week(
                "Cho'qqi",
                "Shaxsiy rekordlar va natijani o'lchash",
                "O'lchov: otjimaniya va o'tirib-turish rekordi",
                "Kardio: 25 daqiqa",
                "Oyoq: og'ir kun",
                "Yuqori tana: og'ir kun",
                "Aylanma mashq: 30 daqiqa",
                "Yakuniy sinov: 1-kun natijalari bilan solishtiring",
            ),
        ),
    ),
    "reading-30": Roadmap(
        outcome="Har kuni o'qish odatga aylangan, 1-2 kitob tugagan",
        weeks=(
            week("Odat boshlanadi", "Har kuni o'qish uchun aniq vaqt va joy bor"),
            week("Diqqat", "Telefonsiz 30 daqiqa chalg'imay o'qiysiz"),
            week("Tushunib o'qish", "Har bobdan asosiy fikrni o'z so'zingiz bilan yozasiz"),
            week("Tezlik", "Kuniga 25-30 betga bemalol yetasiz"),
            week("Yakun", "Kitob tugadi va qisqa xulosa yozildi"),
        ),
    ),
    "code-30": Roadmap(
        outcome="Testlari bor, GitHub'da turgan va README yozilgan kichik loyiha",
        weeks=(
            week(
                "Asoslarni mustahkamlash",
                "Til asoslarida erkin kod yozasiz",
                "O'zgaruvchilar va ma'lumot turlari",
                "Shartlar: if / else",
                "Sikllar: for va while",
                "Funksiyalar va parametrlar",
                "Ro'yxat va lug'atlar",
                "Loyiha: kichik konsol dasturi",
            ),
            week(
                "Toza kod va Git",
                "Kod o'qiladigan va versiyalari saqlanadigan bo'ladi",
                "Yaxshi nomlash va kichik funksiyalar",
                "Git: commit va tarix",
                "Git: branch va merge",
                "Xatolarni qayta ishlash",
                "Fayllar bilan ishlash",
                "Loyiha: kodni GitHub'ga joylash",
            ),
            week(
                "Ma'lumotlar va API",
                "Dastur tashqi dunyo bilan gaplashadi",
                "JSON bilan ishlash",
                "HTTP so'rovlar",
                "Tashqi API'dan ma'lumot olish",
                "SQL: SELECT va WHERE",
                "SQL: INSERT va UPDATE",
                "Loyiha: API'dan olib bazaga saqlovchi dastur",
            ),
            week(
                "Test va sifat",
                "Kodingiz testlar bilan himoyalangan",
                "Birinchi unit test",
                "Testlar bilan refaktoring",
                "Debugger bilan xato qidirish",
                "Algoritmlar: qidiruv va saralash",
                "Murakkablik: O(n) nima",
                "Loyiha: asosiy qismlarga testlar",
            ),
            week(
                "Yakun",
                "Loyiha tayyor va portfolioda",
                "Loyihani yakunlash va README yozish",
                "Portfolio'ga joylash va oy xulosasi",
            ),
        ),
    ),
    "english-30": Roadmap(
        outcome="250+ yangi so'z va o'zingiz haqingizda 3 daqiqa erkin gapira olasiz",
        weeks=(
            week(
                "Tanishuv va kundalik hayot",
                "O'zingiz va kuningiz haqida oddiy gaplar tuzasiz",
                "O'zim haqimda gapirish",
                "Kundalik ishlar: Present Simple",
                "Oila va do'stlar",
                "Raqamlar, vaqt va sanalar",
                "Uy va shahar: there is / there are",
                "Ovqat va do'konda",
                "Hafta takrori: 60 so'z",
            ),
            week(
                "O'tgan zamon",
                "Bo'lib o'tgan voqeani hikoya qilasiz",
                "Past Simple: to'g'ri fe'llar",
                "Past Simple: noto'g'ri fe'llar",
                "Dam olish kunim haqida hikoya",
                "Sayohat so'zlari",
                "Savol berish: Wh- savollar",
                "Qisqa matn o'qish va tarjima",
                "Hafta takrori: 120 so'z",
            ),
            week(
                "Kelajak va rejalar",
                "Reja va taqqoslashlarni ifodalaysiz",
                "going to va will",
                "Ish va kasblar",
                "Sog'liq va tana",
                "Taqqoslash: -er / more",
                "Xat va telefonda rasmiy iboralar",
                "10 daqiqa podkast tinglash",
                "Hafta takrori: 180 so'z",
            ),
            week(
                "Erkin nutq",
                "Fikringizni bildira olasiz",
                "Present Perfect",
                "Fikr bildirish: I think, in my opinion",
                "Film yoki serial haqida gapirish",
                "Maslahat berish: should",
                "5 daqiqa gapirib ovoz yozish",
                "Qisqa esse: 100 so'z",
                "Hafta takrori: 240 so'z",
            ),
            week(
                "Yakun",
                "Oy natijasini tekshirasiz",
                "Oy davomidagi so'zlar testi",
                "O'zingiz haqingizda 3 daqiqalik nutq",
            ),
        ),
    ),
    "early-21": Roadmap(
        outcome="06:30 da turish va kunni reja bilan boshlash odatga aylangan",
        weeks=(
            week("Asta-sekin", "06:30 da turish endi azob emas"),
            week("Kechki tartib", "22:30 gacha uxlashga yotasiz, ertalab tetik turasiz"),
            week("Tong marosimi", "Erta tong — kunning eng samarali, rejalashtirilgan soati"),
        ),
    ),
    "meditation-14": Roadmap(
        outcome="Har kuni 10 daqiqa xotirjamlik — stressga javob tinchroq",
        weeks=(
            week("Nafas", "Nafasga e'tibor qaratib 10 daqiqa o'tira olasiz"),
            week("Tana va fikrlar", "Fikrlarni kuzatib, xotirjam nafasga qaytasiz"),
        ),
    ),
    "steps-30": Roadmap(
        outcome="Oyiga 300 000 qadam va yurish — kun tartibining tabiiy qismi",
        weeks=(
            week("Hisoblash", "Kuniga 10 000 qadamga qancha kerakligini bilasiz"),
            week("Marshrutlar", "Doimiy yurish yo'nalishlaringiz bor"),
            week("Tezlik", "10 000 qadamni 90 daqiqa ichida yurasiz"),
            week("Barqarorlik", "Ob-havo va bandlikdan qat'i nazar yurasiz"),
            week("Yakun", "300 000 qadam marrasi"),
        ),
    ),
    "muaythai-30": Roadmap(
        outcome="Asosiy zarbalar, tepishlar va kombinatsiyalarni qopda 5 raund bajarasiz",
        weeks=(
            week(
                "Stoyka va asosiy zarbalar",
                "To'g'ri stoyka va qo'l zarbalari",
                "Stoyka va harakatlanish",
                "Yengil yugurish va 5 daqiqa soya jangi",
                "Jab va kross",
                "Yugurish va arqon",
                "Teep: oldinga tepish",
                "Kombinatsiya: jab — kross — teep",
            ),
            week(
                "Tepishlar va himoya",
                "Raundxaus tepish va uni to'sish",
                "Raundxaus tepish texnikasi",
                "Yugurish va soya jangi",
                "Tepishni to'sish (chek)",
                "Intervalli yugurish",
                "Hook va aperkot",
                "4 zarbali kombinatsiyalar",
            ),
            week(
                "Tirsak va tizza",
                "Muay Thai'ning o'ziga xos qurollari",
                "Tirsak zarbalari",
                "Yugurish va 10 daqiqa arqon",
                "Tizza zarbalari va klinch asoslari",
                "Intervalli yugurish",
                "Qopda 5 raund, har biri 3 daqiqa",
                "Tirsak va tizza kombinatsiyalari",
            ),
            week(
                "Jang ritmi",
                "Kontratakalar va chidamlilik",
                "Kontratakalar",
                "Yugurish: 30 daqiqa",
                "Juftlikda texnika (sparringsiz)",
                "Intervalli yugurish",
                "Qopda 6 raund, har biri 3 daqiqa",
                "Kondisiya: berpi, sakrash, plank",
            ),
            week(
                "Yakun",
                "O'rganilganlarni bir joyga yig'ish",
                "Barcha kombinatsiyalar takrori",
                "Yakuniy sinov: qopda 5 raund",
            ),
        ),
    ),
}
