"""notification subject

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-26 22:12:08.322878
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("subject_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_notifications_subject_id_users"), "notifications", "users", ["subject_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_notifications_subject_id_users"), "notifications", type_="foreignkey"
    )
    op.drop_column("notifications", "subject_id")
    # ### end Alembic commands ###
