"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 09:55:46.493155
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name_uz", sa.String(length=80), nullable=False),
        sa.Column("name_ru", sa.String(length=80), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["regions.id"], name=op.f("fk_regions_parent_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=13), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_users_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("duration_days", sa.SmallInteger(), nullable=False),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("proof_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification_prompt", sa.Text(), nullable=False),
        sa.Column("stake_allowed", sa.Boolean(), nullable=False),
        sa.Column("min_stake", sa.BigInteger(), nullable=False),
        sa.Column("max_stake", sa.BigInteger(), nullable=False),
        sa.Column("default_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("approval_status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_challenges_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    op.create_table(
        "ledger_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_ledger_transactions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ledger_transactions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_transactions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_ledger_transactions_idempotency_key")),
    )
    op.create_table(
        "score_entries",
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("earned_on", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_score_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("source_key", name=op.f("pk_score_entries")),
    )
    op.create_index("ix_score_entries_user_id", "score_entries", ["user_id"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("available", sa.BigInteger(), nullable=False),
        sa.Column("locked", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("available >= 0", name=op.f("ck_wallets_available_non_negative")),
        sa.CheckConstraint("locked >= 0", name=op.f("ck_wallets_locked_non_negative")),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name=op.f("fk_wallets_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    op.create_table(
        "ledger_postings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("account_kind", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["ledger_transactions.id"],
            name=op.f("fk_ledger_postings_transaction_id_ledger_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_postings")),
    )
    op.create_table(
        "participations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("stake", sa.BigInteger(), nullable=False),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration_days", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("schedule_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("freezes_total", sa.SmallInteger(), nullable=False),
        sa.Column("freezes_used", sa.SmallInteger(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("finished_on", sa.Date(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("stake >= 0", name=op.f("ck_participations_stake_non_negative")),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("fk_participations_challenge_id_challenges"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_participations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participations")),
    )
    op.create_index("ix_participations_status", "participations", ["status"], unique=False)
    op.create_index(
        "uq_participations_one_open_run",
        "participations",
        ["user_id", "challenge_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('scheduled', 'active')"),
    )
    op.create_table(
        "participation_days",
        sa.Column("participation_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participations.id"],
            name=op.f("fk_participation_days_participation_id_participations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("participation_id", "day", name=op.f("pk_participation_days")),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=True),
        sa.Column("participation_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_id"], ["challenges.id"], name=op.f("fk_plans_challenge_id_challenges")
        ),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participations.id"],
            name=op.f("fk_plans_participation_id_participations"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_plans_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
    )
    op.create_table(
        "proofs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("participation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stake_mode", sa.Boolean(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column("task_key", sa.String(length=40), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_key", sa.String(length=300), nullable=True),
        sa.Column("text_note", sa.Text(), nullable=True),
        sa.Column("phash", sa.String(length=64), nullable=True),
        sa.Column("expected_code", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ai_decision", sa.String(length=10), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("ai_reason", sa.Text(), nullable=True),
        sa.Column("ai_model", sa.String(length=80), nullable=True),
        sa.Column("ai_detected_code", sa.String(length=16), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("review_approved", sa.Boolean(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participations.id"],
            name=op.f("fk_proofs_participation_id_participations"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_proofs_reviewer_id_users")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_proofs_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proofs")),
    )
    op.create_index(
        "ix_proofs_participation_day", "proofs", ["participation_id", "for_date"], unique=False
    )
    op.create_index("ix_proofs_status", "proofs", ["status"], unique=False)
    op.create_index("ix_proofs_user_phash", "proofs", ["user_id", "phash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_proofs_user_phash", table_name="proofs")
    op.drop_index("ix_proofs_status", table_name="proofs")
    op.drop_index("ix_proofs_participation_day", table_name="proofs")
    op.drop_table("proofs")
    op.drop_table("plans")
    op.drop_table("participation_days")
    op.drop_index(
        "uq_participations_one_open_run",
        table_name="participations",
        postgresql_where=sa.text("status IN ('scheduled', 'active')"),
    )
    op.drop_index("ix_participations_status", table_name="participations")
    op.drop_table("participations")
    op.drop_table("ledger_postings")
    op.drop_table("wallets")
    op.drop_index("ix_score_entries_user_id", table_name="score_entries")
    op.drop_table("score_entries")
    op.drop_table("ledger_transactions")
    op.drop_table("challenges")
    op.drop_table("users")
    op.drop_table("regions")
    # ### end Alembic commands ###
