"""telegram chat

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 22:54:30.401931
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_users_telegram_chat_id"),
        "users",
        ["telegram_chat_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_telegram_chat_id"), "users", type_="unique")
    op.drop_column("users", "telegram_chat_id")
    # ### end Alembic commands ###
