// Russian for the interface. Key = the Uzbek sentence exactly as written in the code;
// {placeholders} are filled in by t(). Missing keys show in Uzbek.
export const RU: Record<string, string> = {
  // lib/format.ts
  "so'm": "сум",
  "{m} daq": "{m} мин",
  "{h} soat {m} daq": "{h} ч {m} мин",
  "{h} soat": "{h} ч",
  hozirgina: "только что",
  "{n} daqiqa oldin": "{n} мин назад",
  "{n} soat oldin": "{n} ч назад",
  "{n} kun oldin": "{n} дн. назад",
  "Tun bo'yi bedormisiz, {name}? 🌙": "Не спится, {name}? 🌙",
  "Xayrli tong, {name} ☀️": "Доброе утро, {name} ☀️",
  "Xayrli kun, {name} 👋": "Добрый день, {name} 👋",
  "Xayrli kech, {name} 🌆": "Добрый вечер, {name} 🌆",
  Sport: "Спорт",
  Dasturlash: "Программирование",
  Kitob: "Книги",
  "O'qish": "Учёба",
  "Sog'liq": "Здоровье",
  Shaxsiy: "Личное",
  Bajarildi: "Выполнено",
  Freeze: "Заморозка",
  "O'tkazildi": "Пропущено",
  Kutilmoqda: "Ожидает",
  Oldinda: "Впереди",
  "Tekshirilmoqda…": "Проверяется…",
  Tasdiqlandi: "Засчитано",
  "Qabul qilinmadi": "Не принято",
  "Moderator ko'rmoqda": "Смотрит модератор",
  "Boshlanishini kutmoqda": "Ожидает начала",
  Faol: "Активен",
  "Yakunlandi 🏆": "Завершён 🏆",
  Yakunlanmadi: "Не завершён",
  "Bekor qilindi": "Отменён",
  Dushanba: "Понедельник",
  Seshanba: "Вторник",
  Chorshanba: "Среда",
  Payshanba: "Четверг",
  Juma: "Пятница",
  Shanba: "Суббота",
  Yakshanba: "Воскресенье",
  Du: "Пн",
  Se: "Вт",
  Ch: "Ср",
  Pa: "Чт",
  Ju: "Пт",
  Sh: "Сб",
  Ya: "Вс",
  "Server bilan aloqa yo'q. Internetni tekshiring.": "Нет связи с сервером. Проверьте интернет.",
  "Kutilmagan xatolik yuz berdi": "Произошла непредвиденная ошибка",
};
