// Russian for the interface. Key = the Uzbek sentence exactly as written in the code;
// {placeholders} are filled in by t(). Missing keys show in Uzbek.
export const RU: Record<string, string> = {
  // lib/format.ts
  "so'm": "сум",
  "{m} daq": "{m} мин",
  "{h} soat {m} daq": "{h} ч {m} мин",
  "{h} soat": "{h} ч",
  hozirgina: "только что",
  "{n} daqiqa oldin": "{n} мин назад",
  "{n} soat oldin": "{n} ч назад",
  "{n} kun oldin": "{n} дн. назад",
  "Tun bo'yi bedormisiz, {name}? 🌙": "Не спится, {name}? 🌙",
  "Xayrli tong, {name} ☀️": "Доброе утро, {name} ☀️",
  "Xayrli kun, {name} 👋": "Добрый день, {name} 👋",
  "Xayrli kech, {name} 🌆": "Добрый вечер, {name} 🌆",
  Sport: "Спорт",
  Dasturlash: "Программирование",
  Kitob: "Книги",
  "O'qish": "Учёба",
  "Sog'liq": "Здоровье",
  Shaxsiy: "Личное",
  Bajarildi: "Выполнено",
  Freeze: "Заморозка",
  "O'tkazildi": "Пропущено",
  Kutilmoqda: "Ожидает",
  Oldinda: "Впереди",
  "Tekshirilmoqda…": "Проверяется…",
  Tasdiqlandi: "Засчитано",
  "Qabul qilinmadi": "Не принято",
  "Moderator ko'rmoqda": "Смотрит модератор",
  "Boshlanishini kutmoqda": "Ожидает начала",
  Faol: "Активен",
  "Yakunlandi 🏆": "Завершён 🏆",
  Yakunlanmadi: "Не завершён",
  "Bekor qilindi": "Отменён",
  Dushanba: "Понедельник",
  Seshanba: "Вторник",
  Chorshanba: "Среда",
  Payshanba: "Четверг",
  Juma: "Пятница",
  Shanba: "Суббота",
  Yakshanba: "Воскресенье",
  Du: "Пн",
  Se: "Вт",
  Ch: "Ср",
  Pa: "Чт",
  Ju: "Пт",
  Sh: "Сб",
  Ya: "Вс",
  "Server bilan aloqa yo'q. Internetni tekshiring.": "Нет связи с сервером. Проверьте интернет.",
  "Kutilmagan xatolik yuz berdi": "Произошла непредвиденная ошибка",
  "Bosh sahifa": "Главная",
  "Challenge'lar": "Челленджи",
  "Reyting": "Рейтинг",
  "Hamyon": "Кошелёк",
  "Profil": "Профиль",
  "Bosh": "Главная",
  "Challenge": "Челленджи",
  "Moderator": "Модератор",
  "Xabarlar": "Уведомления",
  "Yangi maqsad": "Новая цель",
  "{n} ball": "{n} баллов",
  "Chiqish": "Выйти",
  "Kun hikmati": "Мудрость дня",
  "Murabbiyingiz": "Ваш коуч",
  "Har qadamingizda yoningizda": "Рядом на каждом шагу",
  "Hammasi": "Все",
  "Birinchi challenge'ingizni boshlang — men har kuni siz bilan bo'laman. 💪": "Начните свой первый челлендж — я буду рядом каждый день. 💪",
  "Yopish": "Закрыть",
  "Dam olish kuni": "День отдыха",
  "Bugun boshlagan odat —": "Привычка, начатая сегодня, —",
  "ertangi sizni": "строит вас",
  "quradi.": "завтрашнего.",
  "Maqsadingizni ayting — AI sizga haftalik reja tuzadi": "Назовите цель — ИИ составит план на неделю",
  "Har kuni isbot yuboring, streak'ingiz o'sadi": "Отправляйте доказательство каждый день — серия растёт",
  "Murabbiy qiyin kunlarda ham yoningizda": "Коуч рядом и в трудные дни",
  "Tengdoshlaringiz va hududingiz bilan bellashing": "Соревнуйтесь со сверстниками и своим регионом",
  "Kod yuborildi": "Код отправлен",
  "Telegram botga (ulangan bo'lsa) yoki tasdiqlangan telefonga SMS keladi.": "Придёт в Telegram-бот (если подключён) или SMS на подтверждённый номер.",
  "Parol yangilandi ✅": "Пароль обновлён ✅",
  "Endi yangi parol bilan kiring.": "Теперь войдите с новым паролем.",
  "Parolni tiklash 🔑": "Восстановление пароля 🔑",
  "Kodni Telegram botga yuboramiz. Bot ulanmagan bo'lsa — tasdiqlangan raqamga SMS.": "Отправим код в Telegram-бот. Если бот не подключён — SMS на подтверждённый номер.",
  "Tasdiqlash kodi": "Код подтверждения",
  "8+ belgi, harf va raqam": "8+ символов, буквы и цифры",
  "Yangi parol": "Новый пароль",
  "Parolni yangilash": "Обновить пароль",
  "Kod olish": "Получить код",
  "Esladingizmi?": "Вспомнили?",
  "Kirish": "Войти",
  "Qaytganingizdan xursandmiz 👋": "Рады вас видеть снова 👋",
  "Streak'ingiz sizni kutyapti.": "Ваша серия ждёт вас.",
  "Parol": "Пароль",
  "Parolni unutdingizmi?": "Забыли пароль?",
  "Akkauntingiz yo'qmi?": "Нет аккаунта?",
  "Ro'yxatdan o'ting": "Зарегистрируйтесь",
  "Xush kelibsiz! 🎉": "Добро пожаловать! 🎉",
  "Keling, birinchi maqsadingizni belgilaymiz.": "Давайте определим вашу первую цель.",
  "Yangi boshlanish ✨": "Новое начало ✨",
  "1 daqiqa — va sizning sayohatingiz boshlanadi.": "1 минута — и ваш путь начнётся.",
  "lotin harflari, raqam, _": "латинские буквы, цифры, _",
  "masalan: ali_2008": "например: ali_2008",
  "✓ yaxshi parol": "✓ хороший пароль",
  "7 yoshdan": "с 7 лет",
  "Tug'ilgan sana": "Дата рождения",
  "Hudud": "Регион",
  "Boshlash 🚀": "Начать 🚀",
  "Akkauntingiz bormi?": "Уже есть аккаунт?",
  "Tanlang": "Выберите",
  "Foydalanish shartlari": "Условия использования",
  "Maxfiylik siyosati": "Политика конфиденциальности",
  "yoki": "или",
  "Sessiya topilmadi": "Сессия не найдена",
  "Google orqali qaytadan kiring — bu bir soniya oladi.": "Войдите через Google ещё раз — это займёт секунду.",
  "Ro'yxatdan o'tish": "Регистрация",
  "Oxirgi qadam ✨": "Последний шаг ✨",
  "Google akkauntingiz": "Ваш Google-аккаунт",
  "ulandi. Reyting uchun yoshingiz va hududingiz kerak.": "подключён. Для рейтинга нужны ваш возраст и регион.",
  "Boshqa akkaunt?": "Другой аккаунт?",
  "Guruhga qo'shildingiz! 🤝": "Вы в группе! 🤝",
  "Bugundan birga boshlaymiz.": "Начинаем вместе с сегодняшнего дня.",
  "Havola ishlamayapti 😕": "Ссылка не работает 😕",
  "Taklif": "Приглашение",
  "{owner} sizni birga challenge'ga chaqiryapti": "{owner} зовёт вас в челлендж вместе",
  "{n} kun": "{n} дн.",
  "Haftada {n} kun": "{n} дн. в неделю",
  "{time}/hafta": "{time}/нед.",
  "{n} kishi": "{n} чел.",
  "🤝 Hammangiz bir xil reja bo'yicha harakat qilasiz": "🤝 Все идут по одному плану",
  "🔥 Kim bugun bajarganini guruhda ko'rib turasiz": "🔥 Видно, кто в группе уже справился сегодня",
  "📲 Do'stingiz bajarsa, murabbiy sizga ham xabar beradi": "📲 Когда друг выполнит план, коуч сообщит и вам",
  "Bu guruh to'lgan. {owner}dan yangi guruh ochishini so'rang.": "Группа заполнена. Попросите {owner} создать новую.",
  "Qo'shilish va boshlash 🚀": "Присоединиться и начать 🚀",
  "Ro'yxatdan o'tib qo'shilish 🚀": "Зарегистрироваться и присоединиться 🚀",
  "Akkauntim bor — kirish": "У меня есть аккаунт — войти",
  "AI shaxsiy reja": "Личный план от ИИ",
  "Maqsad va bo'sh vaqtingizni ayting — reja vaqtingizning 80% idan oshmaydi.": "Назовите цель и свободное время — план займёт не больше 80% вашего времени.",
  "Isbot bilan odat": "Привычка с доказательством",
  "Har kuni rasm yoki matn. AI tekshiradi, kunlik kod aldashga yo'l qo'ymaydi.": "Каждый день фото или текст. ИИ проверяет, а код дня не даёт схитрить.",
  "O'zingizga garov": "Ставка на себя",
  "Xohlasangiz pul qo'ying — bajarsangiz 100% qaytadi. Pul hech qachon faqat AI qarori bilan kuymaydi.": "Хотите — поставьте деньги: выполните — вернём 100%. Деньги никогда не сгорают только по решению ИИ.",
  "Murabbiy yoningizda": "Коуч рядом",
  "Yutuqda tabriklaydi, qiyin kunda qo'llab-quvvatlaydi, kechqurun eslatadi.": "Поздравит с победой, поддержит в трудный день, напомнит вечером.",
  "Tengdoshlar reytingi": "Рейтинг сверстников",
  "O'z yoshingiz va hududingizdagilar bilan haftalik bellashuv.": "Еженедельное соревнование с ровесниками и своим регионом.",
  "Streak va ballar": "Серии и баллы",
  "Uzluksiz kunlar ko'proq ball beradi. Freeze — kasal kunlar uchun.": "Дни подряд дают больше баллов. Заморозка — на случай болезни.",
  "Maqsadni ayting": "Назовите цель",
  "Rejani tasdiqlang": "Утвердите план",
  "Har kuni isbot": "Доказательство каждый день",
  "G'alaba 🏆": "Победа 🏆",
  "Tayyor challenge'lar": "Готовые челленджи",
  "Yoki AI bilan o'zingizga moslab tuzing.": "Или составьте свой вместе с ИИ.",
  "Hammasi bepul": "Всё бесплатно",
  "Reja, isbot, murabbiy va reyting — barchasi bepul. Faqat boshlash kerak.": "План, доказательства, коуч и рейтинг — всё бесплатно. Нужно только начать.",
  "Davom etish": "Продолжить",
  "Bepul boshlash": "Начать бесплатно",
  "🔥 Odatlar platformasi · 7 yoshdan": "🔥 Платформа привычек · с 7 лет",
  "O'zingga bergan {promise} bajar.": "Сдержи {promise}, данное себе.",
  "va'dangni": "слово",
  "Maqsadingizni ayting — AI reja tuzadi. Har kuni isbot yuboring, streak'ingizni o'stiring va tengdoshlaringiz bilan bellashing. Qiyin kunlarda murabbiy yoningizda.": "Назовите цель — ИИ составит план. Отправляйте доказательство каждый день, растите серию и соревнуйтесь со сверстниками. В трудные дни коуч рядом.",
  "Qanday ishlaydi?": "Как это работает?",
  "Joriy streak": "Текущая серия",
  "21 kunlik sport — oxirgi hafta!": "21 день спорта — последняя неделя!",
  "Murabbiy": "Коуч",
  "Siz buni uddaladingiz 🔥": "У вас получилось 🔥",
  "14 kun ketma-ket! Maqsadga 7 ish kuni qoldi.": "14 дней подряд! До цели 7 рабочих дней.",
  "2008-yilda tug'ilganlar": "Родившиеся в 2008",
  "4 qadam — va odat sizniki": "4 шага — и привычка ваша",
  "Mukammal kunni kutmang — {today} mukammal qiling.": "Не ждите идеального дня — сделайте {today} идеальным.",
  "bugunni": "сегодняшний",
  "Shartlar": "Условия",
  "Maxfiylik": "Конфиденциальность",
  "Savollar va so'rovlar:": "Вопросы и запросы:",
  "{done}/{total} kun": "{done}/{total} дн.",
  "💰 garov": "💰 ставка",
  "Bugun: bajarildi — barakalla! 🎉": "Сегодня: выполнено — молодец! 🎉",
  "Bugun: {status}": "Сегодня: {status}",
  "Bugun dam olish kuni 🌿": "Сегодня выходной 🌿",
  "Boshlash": "Начать",
  "Bugun {n} ta challenge sizni kutyapti. Kichik qadam — katta natija.": "Сегодня вас ждут челленджи: {n}. Маленький шаг — большой результат.",
  "Bugungi rejalar bajarildi. Siz bilan faxrlanamiz! 🔥": "Планы на сегодня выполнены. Мы гордимся вами! 🔥",
  "Ballar": "Баллы",
  "Eng uzun streak": "Лучшая серия",
  "Yakunlangan": "Завершённые",
  "Challenge'larim": "Мои челленджи",
  "+ Yangi": "+ Новый",
  "Hali challenge yo'q": "Челленджей пока нет",
  "Maqsadingizni ayting — AI 30 soniyada shaxsiy reja tuzadi. Yoki tayyor challenge'lardan birini tanlang.": "Назовите цель — ИИ за 30 секунд составит личный план. Или выберите готовый челлендж.",
  "Menga reja tuz ✨": "Составь мне план ✨",
  "Katalog": "Каталог",
  "Tarix": "История",
  "Qiyinlik {level}/5": "Сложность {level}/5",
  "Sinalgan dasturlar. Har biri — yangi odat sari aniq yo'l.": "Проверенные программы. Каждая — чёткий путь к новой привычке.",
  "✨ O'zimga moslab tuzish": "✨ Составить под себя",
  "{n} kun/hafta": "{n} дн./нед.",
  "garov": "ставка",
  "Qo'shildingiz! 🚀": "Вы участвуете! 🚀",
  "Bugundan boshlab har kuni bir qadam.": "С сегодняшнего дня — шаг каждый день.",
  "{n} ishtirokchi": "Участников: {n}",
  "rasm yoki matn": "фото или текст",
  "rasm": "фото",
  "Haftalik reja": "План на неделю",
  "(qo'shimcha)": "(доп.)",
  "Dam olish 🌿": "Отдых 🌿",
  "Hozircha hammasi bepul 🎁": "Пока всё бесплатно 🎁",
  "Ball, streak, reyting va murabbiy — barchasi siz uchun ochiq.": "Баллы, серии, рейтинг и коуч — всё открыто для вас.",
  "Qanday boshlaymiz?": "Как начнём?",
  "Oddiy": "Обычный",
  "Ball, streak va reyting uchun": "За баллы, серию и рейтинг",
  "Garov bilan": "Со ставкой",
  "Pul muzlatiladi, bajarsangiz 100% qaytadi": "Деньги замораживаются, при выполнении вернутся 100%",
  "Bu challenge uchun mavjud emas": "Недоступно для этого челленджа",
  "Challenge oxirigacha bajarilsa, garov to'liq qaytadi. Bajarilmasa — platformada qoladi. Pul hech qachon faqat AI qarori bilan kuymaydi: shubhali holatlarni inson tekshiradi.": "Если челлендж выполнен до конца, ставка возвращается полностью. Если нет — остаётся на платформе. Деньги никогда не сгорают только по решению ИИ: спорные случаи проверяет человек.",
  "Avval telefon raqamingizni {link}.": "Сначала {link} номер телефона.",
  "tasdiqlang": "подтвердите",
  "Hamyonda {sum} bor.": "В кошельке {sum}.",
  "Hisobni to'ldiring": "Пополните счёт",
  "{sum} bilan boshlash": "Начать с {sum}",
  "Rasm yoki qisqa matn qo'shing": "Добавьте фото или короткий текст",
  "Isbot yuborildi 📨": "Доказательство отправлено 📨",
  "Tekshiruvdan so'ng natijani ko'rasiz.": "Результат увидите после проверки.",
  "qo'shimcha": "доп.",
  "Sabab: {reason}. Qayta urinib ko'ring — hali vaqt bor 💪": "Причина: {reason}. Попробуйте ещё раз — время ещё есть 💪",
  "Qayta": "Заново",
  "Isbot": "Доказательство",
  "Tanlangan rasm": "Выбранное фото",
  "Rasm olish yoki tanlash": "Сделать или выбрать фото",
  "Qisqa izoh (ixtiyoriy)": "Короткий комментарий (необязательно)",
  "Bugun nima qildingiz?": "Что вы сделали сегодня?",
  "Bekor": "Отмена",
  "Yuborish": "Отправить",
  "Vazifa nomi": "Название задачи",
  "Kamaytirish": "Уменьшить",
  "Oshirish": "Увеличить",
  "Majburiy": "Обязательно",
  "Qo'shimcha": "Доп.",
  "O'chirish": "Удалить",
  "Yangi vazifa": "Новая задача",
  "+ vazifa qo'shish": "+ добавить задачу",
  "3 oyda backend dasturchi bo'lish": "Стать backend-разработчиком за 3 месяца",
  "Ingliz tilida erkin gapirish": "Свободно говорить по-английски",
  "Har kuni sport bilan shug'ullanish": "Заниматься спортом каждый день",
  "Yiliga 24 ta kitob o'qish": "Читать 24 книги в год",
  "Erta turishni odat qilish": "Привыкнуть рано вставать",
  "Vaqt kam": "Мало времени",
  "Charchoq": "Усталость",
  "Telefon chalg'itadi": "Отвлекает телефон",
  "Motivatsiya tez so'nadi": "Мотивация быстро угасает",
  "Boshlash qiyin": "Трудно начать",
  "Ish kunlari 1 soat": "По будням 1 час",
  "Har kuni 30 daq": "Каждый день 30 мин",
  "Kechqurun 2 soat": "Вечером 2 часа",
  "Katta o'zgarish aniq maqsaddan boshlanadi. Nimaga erishmoqchisiz?": "Большие перемены начинаются с чёткой цели. Чего вы хотите достичь?",
  "Sababingiz — qiyin kunlardagi yoqilg'ingiz. Uni yozib qo'yamiz.": "Ваша причина — топливо на трудные дни. Запишем её.",
  "Nima xalaqit berishini bilsak, rejani shunga moslaymiz.": "Зная, что мешает, мы подстроим под это план.",
  "Rejani faqat bo'sh vaqtingizning 80% iga tuzamiz — hayotga ham joy qoladi.": "План займёт только 80% свободного времени — останется место и для жизни.",
  "Qaysi yo'ldan boramiz?": "Какой путь выберем?",
  "Ikkalasi ham to'g'ri. Muhimi — bugun boshlash.": "Оба верные. Главное — начать сегодня.",
  "4 ta savol — va AI maqsadingizga, vaqtingizga mos shaxsiy haftalik reja tuzadi.": "4 вопроса — и ИИ составит личный план на неделю под вашу цель и время.",
  "Tayyor challenge": "Готовый челлендж",
  "Sport, kitob, kod, til, erta turish — sinalgan challenge'lardan birini tanlang.": "Спорт, книги, код, языки, ранний подъём — выберите один из проверенных челленджей.",
  "Katalogni ochish": "Открыть каталог",
  "Maqsadingiz": "Ваша цель",
  "Masalan: 3 oyda backend dasturchi bo'lish": "Например: стать backend-разработчиком за 3 месяца",
  "Bu siz uchun nega muhim?": "Почему это важно для вас?",
  "Masalan: yaxshi ishga kirib, oilamga yordam berish": "Например: устроиться на хорошую работу и помогать семье",
  "Hozirgi darajangiz": "Ваш текущий уровень",
  "Masalan: Python asoslarini bilaman": "Например: знаю основы Python",
  "Nima xalaqit beradi? (bir nechtasini tanlang)": "Что мешает? (можно выбрать несколько)",
  "bo'sh emas": "занят",
  "Orqaga": "Назад",
  "Keyingisi": "Далее",
  "Reja tuzish": "Составить план",
  "Reja saqlandi": "План сохранён",
  "Sayohat boshlandi! 🚀": "Путь начался! 🚀",
  "Birinchi qadam — eng muhimi. Siz uni qo'ydingiz.": "Первый шаг — самый важный. Вы его сделали.",
  "✨ Siz uchun tuzilgan reja": "✨ План, составленный для вас",
  "{time} majburiy": "{time} обязательно",
  "Istalgancha o'zgartiring. Chiziq — bo'sh vaqtingizning 80% i.": "Меняйте как угодно. Полоса — 80% вашего свободного времени.",
  "Saqlash": "Сохранить",
  "Challenge sahifasiga o'tish": "Перейти к челленджу",
  "Bugungi kun yopildi! Siz o'zingizga bergan va'dada turdingiz. 🔥": "День закрыт! Вы сдержали слово, данное себе. 🔥",
  "Zo'r! Har bir bajarilgan kun — kelajakdagi o'zingizga sovg'a. 🎁": "Отлично! Каждый выполненный день — подарок себе в будущем. 🎁",
  "Barakalla! Tomchi-tomchi ko'l bo'lur. 💧": "Молодец! Капля за каплей — и море. 💧",
  "Streak: {n} kun": "Серия: {n} дн.",
  "Challenge bekor qilindi": "Челлендж отменён",
  "Garov hamyoningizga qaytarildi.": "Ставка возвращена в кошелёк.",
  "kun": "дн.",
  "Streak": "Серия",
  "qolmadi": "не осталось",
  "Garov": "Ставка",
  "Siz buni uddaladingiz! Bu g'alaba — faqat sizniki. 🏆": "У вас получилось! Эта победа — только ваша. 🏆",
  "Challenge {date} kuni boshlanadi. Tayyorlaning! 💪": "Челлендж начнётся {date}. Готовьтесь! 💪",
  "Bu safar chiqmadi — lekin bu oxiri emas. Tayyor bo'lsangiz, qaytadan boshlaymiz. 🌱": "В этот раз не вышло — но это не конец. Будете готовы — начнём заново. 🌱",
  "Bugun dam olish kuni. Tiklanish ham mashqning bir qismi. 🌿": "Сегодня выходной. Восстановление — тоже часть тренировки. 🌿",
  "Bugungi majburiy vazifalar bajarildi! Qo'shimchalar — bonus ball. ⭐": "Обязательные задачи на сегодня выполнены! Дополнительные — бонусные баллы. ⭐",
  "Bugun {n} ta majburiy vazifa qoldi. Boshladik! 🔥": "Сегодня осталось обязательных задач: {n}. Поехали! 🔥",
  "Bugungi kod — qog'ozga yozib, rasmda ko'rsating": "Код дня — напишите на бумаге и покажите на фото",
  "Boshlanmasdan bekor qilish": "Отменить до начала",
  "Kalendar": "Календарь",
  "Bekor qilasizmi?": "Отменить?",
  "Challenge hali boshlanmagan, shuning uchun garov to'liq qaytariladi.": "Челлендж ещё не начался, поэтому ставка вернётся полностью.",
  "Challenge hali boshlanmagan, shuning uchun hech narsa yo'qotmaysiz.": "Челлендж ещё не начался, поэтому вы ничего не теряете.",
  "Qolaman": "Остаюсь",
  "Bekor qilish": "Отменить",
  "bugun bajardi": "сегодня выполнил(а)",
  "bugun hali": "сегодня ещё нет",
  "tekshirilmoqda": "проверяется",
  "freeze": "заморозка",
  "o'tkazib yubordi": "пропустил(а)",
  "dam olish": "выходной",
  "👏 {name} olqishingizni oldi!": "👏 {name} получил(а) ваши аплодисменты!",
  "{name}ni olqishlash": "Поаплодировать {name}",
  "(siz)": "(вы)",
  "Birga kuchliroq": "Вместе сильнее",
  "Do'stlaringizni taklif qiling: bir xil reja, umumiy reyting. Kim bugun bajarganini ko'rib turasiz — va orqada qolish uyat bo'ladi 😉": "Пригласите друзей: один план, общий рейтинг. Вы видите, кто сегодня выполнил — и отставать будет неловко 😉",
  "Do'stlarni taklif qilish": "Пригласить друзей",
  "Men bilan birga challenge'ni boshla! Har kuni bir-birimizni ko'rib turamiz 🔥": "Начни челлендж вместе со мной! Будем каждый день видеть успехи друг друга 🔥",
  "Nusxalab bo'lmadi — havolani qo'lda belgilang.": "Не удалось скопировать — выделите ссылку вручную.",
  "Guruh": "Группа",
  "Taklif havolasi": "Ссылка-приглашение",
  "Nusxalash": "Копировать",
  "Telegram'da ulashish": "Поделиться в Telegram",
  "Haqorat yoki bezorilik": "Оскорбления или травля",
  "Nomaqbul username": "Недопустимое имя",
  "Spam": "Спам",
  "Boshqa": "Другое",
  "Shikoyat yuborildi": "Жалоба отправлена",
  "Moderator ko'rib chiqadi. Rahmat, jamiyatni toza saqlashga yordam berdingiz.": "Модератор рассмотрит. Спасибо, что помогаете сохранять сообщество чистым.",
  "{name} haqida shikoyat": "Жалоба на {name}",
  "Nima bo'ldi? (ixtiyoriy)": "Что случилось? (необязательно)",
  "Nishonlar": "Значки",
  "Murabbiy xabarlari": "Сообщения коуча",
  "Yutuqlaringiz, eslatmalar va qo'llab-quvvatlash — hammasi shu yerda.": "Ваши успехи, напоминания и поддержка — всё здесь.",
  "Men har kuni siz bilanman. Yiqilsangiz — turishga yordam beraman. 🤝": "Я с вами каждый день. Упадёте — помогу подняться. 🤝",
  "Hali xabar yo'q": "Сообщений пока нет",
  "Challenge boshlang — birinchi xabarim darhol keladi.": "Начните челлендж — моё первое сообщение придёт сразу.",
  "SMS'dagi 6 xonali kodni kiriting.": "Введите 6-значный код из SMS.",
  "Telefon tasdiqlandi ✅": "Телефон подтверждён ✅",
  "{year}-yil": "{year} г.",
  "eng uzun streak": "лучшая серия",
  "Telefon raqam": "Номер телефона",
  "{phone} tasdiqlangan": "{phone} подтверждён",
  "Garovli challenge'lar va parolni tiklash uchun kerak.": "Нужен для челленджей со ставкой и восстановления пароля.",
  "Parolni tiklash va akkaunt xavfsizligi uchun kerak.": "Нужен для восстановления пароля и безопасности аккаунта.",
  "Bolalar ota-ona raqamidan foydalanishi mumkin.": "Дети могут использовать номер родителя.",
  "Telegram orqali tasdiqlash": "Подтвердить через Telegram",
  "Botda «📱 Raqamni yuborish» tugmasini bosing — kod yozish shart emas. Qaytganingizda sahifa o'zi yangilanadi.": "Нажмите в боте «📱 Отправить номер» — вводить код не нужно. Когда вернётесь, страница обновится сама.",
  "📲 Avval pastdagi {bot}ni ulang — raqamingizni u orqali bir bosishda, bepul tasdiqlaysiz.": "📲 Сначала подключите {bot} ниже — через него номер подтверждается в одно нажатие и бесплатно.",
  "Telegram bot": "Telegram-бота",
  "SMS orqali: raqam": "Через SMS: номер",
  "SMS kod": "Код из SMS",
  "Tasdiqlash": "Подтвердить",
  "Ertalab — bugungi reja": "Утром — план на сегодня",
  "Kechqurun — bajarilmagan vazifalar": "Вечером — невыполненные задачи",
  "Isbotni bir bosishda yuborish": "Доказательство в одно нажатие",
  "Telegram uzildi": "Telegram отключён",
  "Eslatmalar endi faqat saytda ko'rinadi.": "Напоминания теперь видны только на сайте.",
  "Ulangan — murabbiy Telegram'da yozadi": "Подключено — коуч пишет в Telegram",
  "Botni ochish": "Открыть бота",
  "Uzish": "Отключить",
  "Telegram'da ochish": "Открыть в Telegram",
  "Telegram'da {start} ni bosing — shu sahifa o'zi yangilanadi. Havola 10 daqiqa amal qiladi.": "Нажмите {start} в Telegram — эта страница обновится сама. Ссылка действует 10 минут.",
  "Telegram'ni ulash": "Подключить Telegram",
  "Eslatmalarni Telegram'da oling": "Получайте напоминания в Telegram",
  "Isbotni ham botning o'zida yuborasiz 📸": "Доказательства можно отправлять прямо в боте 📸",
  "Yuklab olindi": "Скачано",
  "Rasm havolalari 15 daqiqa ishlaydi — kerak bo'lsa, hozir saqlab oling.": "Ссылки на фото действуют 15 минут — если нужно, сохраните их сейчас.",
  "Akkaunt o'chirildi": "Аккаунт удалён",
  "Sizni yana kutib qolamiz. O'zingizga yaxshi qarang 🌱": "Будем ждать вас снова. Берегите себя 🌱",
  "Ma'lumotlarim": "Мои данные",
  "Ma'lumotlaringiz sizniki: nusxasini oling yoki akkauntni butunlay o'chiring.": "Ваши данные принадлежат вам: скачайте копию или удалите аккаунт полностью.",
  "Nusxasini yuklab olish": "Скачать копию",
  "Akkauntni o'chirish": "Удалить аккаунт",
  "Akkauntni o'chirasizmi?": "Удалить аккаунт?",
  "🗑 Username, telefon, email, Google va Telegram ulanishi o'chiriladi": "🗑 Удалятся имя, телефон, email, привязки Google и Telegram",
  "📸 Barcha isbot rasmlari va yozuvlaringiz o'chiriladi": "📸 Удалятся все фото доказательств и ваши записи",
  "🏆 Reytingdan chiqasiz, faol challenge'lar yopiladi": "🏆 Вы выйдете из рейтинга, активные челленджи закроются",
  "⚠️ Buni qaytarib bo'lmaydi": "⚠️ Это нельзя отменить",
  "Tasdiqlash uchun {name} deb yozing": "Для подтверждения введите {name}",
  "Ruxsat berilmadi": "Разрешение не дано",
  "Brauzer sozlamalarida bu sayt uchun bildirishnomalarni yoqing.": "Включите уведомления для этого сайта в настройках браузера.",
  "Bildirishnomalar yoqildi 🔔": "Уведомления включены 🔔",
  "Murabbiy xabarlari endi telefoningizga keladi.": "Сообщения коуча теперь будут приходить на телефон.",
  "Ilova va bildirishnomalar": "Приложение и уведомления",
  "Telefonga ilova sifatida o'rnatish": "Установить на телефон как приложение",
  "iPhone'da: Safari'da {steps}. Shundan keyin bildirishnomalarni ham yoqasiz.": "На iPhone: в Safari {steps}. После этого можно включить и уведомления.",
  "Ulashish → Bosh ekranga qo'shish": "Поделиться → На экран «Домой»",
  "Bu qurilmada bildirishnomalar yoqilgan": "Уведомления на этом устройстве включены",
  "Bildirishnomalarni yoqish": "Включить уведомления",
  "Har bir bajarilgan kun — ball. Uzluksiz streak — ko'proq ball.": "Каждый выполненный день — баллы. Серия без пропусков — больше баллов.",
  "Umumiy": "Общий",
  "Tengdoshlar": "Ровесники",
  "Hafta": "Неделя",
  "Oy": "Месяц",
  "Guruh hali kichik": "Группа пока маленькая",
  "Maxfiylik uchun 10 kishidan kam guruhlar ko'rsatilmaydi. Do'stlaringizni taklif qiling — birga qiziqroq!": "Ради конфиденциальности группы меньше 10 человек не показываются. Пригласите друзей — вместе интереснее!",
  "Hali hech kim yo'q": "Пока никого нет",
  "Birinchi bo'ling! Bugungi vazifani bajaring — ismingiz shu yerda chiqadi.": "Будьте первым! Выполните задачу на сегодня — и ваше имя появится здесь.",
  "Kuchli uchlik! Siz ham shu yerda bo'lishingiz mumkin.": "Сильная тройка! Вы тоже можете быть здесь.",
  "Sizning o'rningiz": "Ваше место",
  "Hali ball yo'q — bugun boshlang!": "Баллов пока нет — начните сегодня!",
  "Hisob to'ldirildi": "Счёт пополнен",
  "Yechib olindi": "Выведено",
  "Garov muzlatildi": "Ставка заморожена",
  "Garov qaytarildi 🎉": "Ставка возвращена 🎉",
  "Garov platformaga o'tdi": "Ставка перешла платформе",
  "{sum} qo'shildi": "Добавлено {sum}",
  "Garov rejimi va hamyon keyinroq ochiladi. Hozir esa odatlaringizga e'tibor bering!": "Режим ставок и кошелёк откроются позже. А пока сосредоточьтесь на привычках!",
  "Garov — o'zingizga bergan va'daning kafolati.": "Ставка — гарантия обещания, данного себе.",
  "Mavjud balans": "Доступный баланс",
  "Muzlatilgan: {sum}": "Заморожено: {sum}",
  "Hisobni to'ldirish": "Пополнение счёта",
  "Test rejimi: pul darhol qo'shiladi. Ishga tushganda Payme / Click orqali bo'ladi.": "Тестовый режим: деньги добавляются сразу. После запуска — через Payme / Click.",
  "Hali operatsiya yo'q": "Операций пока нет",
  "Garovli challenge boshlaganingizda bu yerda ko'rinadi.": "Появятся здесь, когда начнёте челлендж со ставкой.",
  "Hozircha hammasi bepul": "Пока всё бесплатно",
  "Rad etish sababini yozing": "Укажите причину отказа",
  "Foydalanuvchi uni ko'radi.": "Пользователь её увидит.",
  "Rad etildi": "Отклонено",
  "⚠️ Nomaqbul kontent shubhasi": "⚠️ Подозрение на недопустимый контент",
  "Rasm yashirilgan — ko'rsatish": "Фото скрыто — показать",
  "(ishonch {n}%)": "(уверенность {n}%)",
  "Izoh (rad etishda majburiy)": "Комментарий (обязателен при отказе)",
  "Rad etish": "Отклонить",
  "Haqorat": "Оскорбление",
  "Shikoyat yopildi": "Жалоба закрыта",
  "{name} username'i tozalandi": "Имя {name} сброшено",
  "Shikoyatlar": "Жалобы",
  "Ochiq shikoyat yo'q ✨": "Открытых жалоб нет ✨",
  "{n} ta shikoyat": "Жалоб: {n}",
  "Username'ni tozalash": "Сбросить имя",
  "Ruxsat yo'q": "Нет доступа",
  "Moderator paneli": "Панель модератора",
  "Shubhali isbotlar. Pulli challenge'lar birinchi — adolatli va tez qaror qiling.": "Спорные доказательства. Платные челленджи первыми — решайте справедливо и быстро.",
  "Analitika": "Аналитика",
  "Kunlar yopildi": "Дни закрыты",
  "Kunlarni yopish": "Закрыть дни",
  "Eslatmalar yuborildi": "Напоминания отправлены",
  "Kechki eslatma": "Вечернее напоминание",
  "Navbat bo'sh": "Очередь пуста",
  "Hozircha tekshirishga isbot yo'q.": "Пока нет доказательств на проверку.",
  "Faol foydalanuvchilar — oxirgi 30 kun": "Активные пользователи — последние 30 дней",
  "Grafik": "График",
  "Jadval": "Таблица",
  "Sana": "Дата",
  "Yangi": "Новые",
  "{active} faol · {new} yangi": "{active} активн. · {new} нов.",
  "Voronka": "Воронка",
  "Ro'yxatdan o'tdi": "Зарегистрировался",
  "Challenge boshladi": "Начал челлендж",
  "Isbot yubordi": "Отправил доказательство",
  "Kunni bajardi": "Выполнил день",
  "Challenge'ni yakunladi": "Завершил челлендж",
  "Odamlar keladimi, qaytadimi, oxirigacha yetadimi.": "Приходят ли люди, возвращаются ли, доходят ли до конца.",
  "{warning} oxirgi 30 kunda {n} ta isbot AI ishlamagani uchun tekshiruvsiz o'tdi. AI kalitlari va limitlarini tekshiring ({command}).": "{warning} за последние 30 дней доказательств без проверки из-за недоступности ИИ: {n}. Проверьте ключи и лимиты ИИ ({command}).",
  "Ogohlantirish:": "Внимание:",
  "Foydalanuvchilar": "Пользователи",
  "+{week} bu hafta · +{month} 30 kunda": "+{week} за неделю · +{month} за 30 дней",
  "Faol (kun / hafta / oy)": "Активные (день / неделя / месяц)",
  "kamida bitta isbot yuborganlar": "отправившие хотя бы одно доказательство",
  "Qaytish": "Возврат",
  "ertasiga · 2-haftada": "на следующий день · на 2-й неделе",
  "Yakunlash": "Завершение",
  "{n} ta challenge davom etmoqda": "Идёт челленджей: {n}",
  "Guruhlar": "Группы",
  "{n} ta qatnashuv guruhda": "Участий в группах: {n}",
  "ulangan foydalanuvchilar": "подключённые пользователи",
  "Isbotlar (30 kun)": "Доказательства (30 дней)",
  "{share} tasdiqlangan": "{share} подтверждено",
  "Moderator navbati": "Очередь модератора",
  "{n} ta nomaqbul shubhasi (30 kun)": "Подозрений на недопустимое: {n} (30 дней)",
};
