// Russian for the interface. Key = the Uzbek sentence exactly as written in the code;
// {placeholders} are filled in by t(). Missing keys show in Uzbek.
export const RU: Record<string, string> = {
  // lib/format.ts
  "so'm": "сум",
  "{m} daq": "{m} мин",
  "{h} soat {m} daq": "{h} ч {m} мин",
  "{h} soat": "{h} ч",
  hozirgina: "только что",
  "{n} daqiqa oldin": "{n} мин назад",
  "{n} soat oldin": "{n} ч назад",
  "{n} kun oldin": "{n} дн. назад",
  "Tun bo'yi bedormisiz, {name}? 🌙": "Не спится, {name}? 🌙",
  "Xayrli tong, {name} ☀️": "Доброе утро, {name} ☀️",
  "Xayrli kun, {name} 👋": "Добрый день, {name} 👋",
  "Xayrli kech, {name} 🌆": "Добрый вечер, {name} 🌆",
  Sport: "Спорт",
  Dasturlash: "Программирование",
  Kitob: "Книги",
  "O'qish": "Учёба",
  "Sog'liq": "Здоровье",
  Shaxsiy: "Личное",
  Bajarildi: "Выполнено",
  Freeze: "Заморозка",
  "O'tkazildi": "Пропущено",
  Kutilmoqda: "Ожидает",
  Oldinda: "Впереди",
  "Tekshirilmoqda…": "Проверяется…",
  Tasdiqlandi: "Засчитано",
  "Qabul qilinmadi": "Не принято",
  "Moderator ko'rmoqda": "Смотрит модератор",
  "Boshlanishini kutmoqda": "Ожидает начала",
  Faol: "Активен",
  "Yakunlandi 🏆": "Завершён 🏆",
  Yakunlanmadi: "Не завершён",
  "Bekor qilindi": "Отменён",
  Dushanba: "Понедельник",
  Seshanba: "Вторник",
  Chorshanba: "Среда",
  Payshanba: "Четверг",
  Juma: "Пятница",
  Shanba: "Суббота",
  Yakshanba: "Воскресенье",
  Du: "Пн",
  Se: "Вт",
  Ch: "Ср",
  Pa: "Чт",
  Ju: "Пт",
  Sh: "Сб",
  Ya: "Вс",
  "Server bilan aloqa yo'q. Internetni tekshiring.": "Нет связи с сервером. Проверьте интернет.",
  "Kutilmagan xatolik yuz berdi": "Произошла непредвиденная ошибка",
  "Bosh sahifa": "Главная",
  "Challenge'lar": "Челленджи",
  "Reyting": "Рейтинг",
  "Hamyon": "Кошелёк",
  "Profil": "Профиль",
  "Bosh": "Главная",
  "Challenge": "Челленджи",
  "Moderator": "Модератор",
  "Xabarlar": "Уведомления",
  "Yangi maqsad": "Новая цель",
  "{n} ball": "{n} баллов",
  "Chiqish": "Выйти",
  "Kun hikmati": "Мудрость дня",
  "Murabbiyingiz": "Ваш коуч",
  "Har qadamingizda yoningizda": "Рядом на каждом шагу",
  "Hammasi": "Все",
  "Birinchi challenge'ingizni boshlang — men har kuni siz bilan bo'laman. 💪": "Начните свой первый челлендж — я буду рядом каждый день. 💪",
  "Yopish": "Закрыть",
  "Dam olish kuni": "День отдыха",
  "Bugun boshlagan odat —": "Привычка, начатая сегодня, —",
  "ertangi sizni": "строит вас",
  "quradi.": "завтрашнего.",
  "Maqsadingizni ayting — AI sizga haftalik reja tuzadi": "Назовите цель — ИИ составит план на неделю",
  "Har kuni isbot yuboring, streak'ingiz o'sadi": "Отправляйте доказательство каждый день — серия растёт",
  "Murabbiy qiyin kunlarda ham yoningizda": "Коуч рядом и в трудные дни",
  "Tengdoshlaringiz va hududingiz bilan bellashing": "Соревнуйтесь со сверстниками и своим регионом",
  "Kod yuborildi": "Код отправлен",
  "Telegram botga (ulangan bo'lsa) yoki tasdiqlangan telefonga SMS keladi.": "Придёт в Telegram-бот (если подключён) или SMS на подтверждённый номер.",
  "Parol yangilandi ✅": "Пароль обновлён ✅",
  "Endi yangi parol bilan kiring.": "Теперь войдите с новым паролем.",
  "Parolni tiklash 🔑": "Восстановление пароля 🔑",
  "Kodni Telegram botga yuboramiz. Bot ulanmagan bo'lsa — tasdiqlangan raqamga SMS.": "Отправим код в Telegram-бот. Если бот не подключён — SMS на подтверждённый номер.",
  "Tasdiqlash kodi": "Код подтверждения",
  "8+ belgi, harf va raqam": "8+ символов, буквы и цифры",
  "Yangi parol": "Новый пароль",
  "Parolni yangilash": "Обновить пароль",
  "Kod olish": "Получить код",
  "Esladingizmi?": "Вспомнили?",
  "Kirish": "Войти",
  "Qaytganingizdan xursandmiz 👋": "Рады вас видеть снова 👋",
  "Streak'ingiz sizni kutyapti.": "Ваша серия ждёт вас.",
  "Parol": "Пароль",
  "Parolni unutdingizmi?": "Забыли пароль?",
  "Akkauntingiz yo'qmi?": "Нет аккаунта?",
  "Ro'yxatdan o'ting": "Зарегистрируйтесь",
  "Xush kelibsiz! 🎉": "Добро пожаловать! 🎉",
  "Keling, birinchi maqsadingizni belgilaymiz.": "Давайте определим вашу первую цель.",
  "Yangi boshlanish ✨": "Новое начало ✨",
  "1 daqiqa — va sizning sayohatingiz boshlanadi.": "1 минута — и ваш путь начнётся.",
  "lotin harflari, raqam, _": "латинские буквы, цифры, _",
  "masalan: ali_2008": "например: ali_2008",
  "✓ yaxshi parol": "✓ хороший пароль",
  "7 yoshdan": "с 7 лет",
  "Tug'ilgan sana": "Дата рождения",
  "Hudud": "Регион",
  "Boshlash 🚀": "Начать 🚀",
  "Akkauntingiz bormi?": "Уже есть аккаунт?",
  "Tanlang": "Выберите",
  "Foydalanish shartlari": "Условия использования",
  "Maxfiylik siyosati": "Политика конфиденциальности",
  "yoki": "или",
  "Sessiya topilmadi": "Сессия не найдена",
  "Google orqali qaytadan kiring — bu bir soniya oladi.": "Войдите через Google ещё раз — это займёт секунду.",
  "Ro'yxatdan o'tish": "Регистрация",
  "Oxirgi qadam ✨": "Последний шаг ✨",
  "Google akkauntingiz": "Ваш Google-аккаунт",
  "ulandi. Reyting uchun yoshingiz va hududingiz kerak.": "подключён. Для рейтинга нужны ваш возраст и регион.",
  "Boshqa akkaunt?": "Другой аккаунт?",
  "Guruhga qo'shildingiz! 🤝": "Вы в группе! 🤝",
  "Bugundan birga boshlaymiz.": "Начинаем вместе с сегодняшнего дня.",
  "Havola ishlamayapti 😕": "Ссылка не работает 😕",
  "Taklif": "Приглашение",
  "{owner} sizni birga challenge'ga chaqiryapti": "{owner} зовёт вас в челлендж вместе",
  "{n} kun": "{n} дн.",
  "Haftada {n} kun": "{n} дн. в неделю",
  "{time}/hafta": "{time}/нед.",
  "{n} kishi": "{n} чел.",
  "🤝 Hammangiz bir xil reja bo'yicha harakat qilasiz": "🤝 Все идут по одному плану",
  "🔥 Kim bugun bajarganini guruhda ko'rib turasiz": "🔥 Видно, кто в группе уже справился сегодня",
  "📲 Do'stingiz bajarsa, murabbiy sizga ham xabar beradi": "📲 Когда друг выполнит план, коуч сообщит и вам",
  "Bu guruh to'lgan. {owner}dan yangi guruh ochishini so'rang.": "Группа заполнена. Попросите {owner} создать новую.",
  "Qo'shilish va boshlash 🚀": "Присоединиться и начать 🚀",
  "Ro'yxatdan o'tib qo'shilish 🚀": "Зарегистрироваться и присоединиться 🚀",
  "Akkauntim bor — kirish": "У меня есть аккаунт — войти",
};
